### ISSUE TITLE
Lost host and passwd parameters when using DBPool to call pymysql

### ISSUE THREAD

**Issue by canotf** [PyMySQL/PyMySQL#1017]
**Describe the bug**

Traceback (most recent call last):
  File "G:/Github/AestateFramework/testOpera/operas/cache_test/cache_t2.py", line 18, in <module>
    rxc.findAllById(id=10)
  File "G:\Github\AestateFramework\aestate\work\Annotation.py", line 278, in _wrapper_
    result = obj.db_util.select(sql=sub_sql, params=params, mode=EX_MODEL.SELECT)
  File "G:\Github\AestateFramework\aestate\work\sql\ExecuteSql.py", line 77, in select
    db = self.get_conn()
  File "G:\Github\AestateFramework\aestate\work\sql\ExecuteSql.py", line 64, in get_conn
    conn = self.POOL.connection()
  File "G:\Github\AestateFramework\aestate\opera\DBPool\pooled_db.py", line 202, in connection
    con = self.steady_connection()
  File "G:\Github\AestateFramework\aestate\opera\DBPool\pooled_db.py", line 152, in steady_connection
    self._failures, self._ping, True, *self._args, **self._kwargs)
  File "G:\Github\AestateFramework\aestate\opera\DBPool\steady_db.py", line 44, in connect
    failures, ping, closeable, *args, **kwargs)
  File "G:\Github\AestateFramework\aestate\opera\DBPool\steady_db.py", line 97, in __init__
    self._store(self._create())
  File "G:\Github\AestateFramework\aestate\opera\DBPool\steady_db.py", line 115, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\connections.py", line 932, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\_auth.py", line 239, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Anaconda3\envs\aestate\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user 'root'@'%' to database 'demo'")

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE demo
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for demo
-- ----------------------------
DROP TABLE IF EXISTS `demo`;
CREATE TABLE `demo`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `password` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `a` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 86127 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

```

Code:

https://gitee.com/aecode/aestate/blob/main/aestate/work/sql/ExecuteSql.py
line 65

**Expected behavior**
I don’t know why the host and passwd parameters will be lost after connecting to ssl when using DBPool to call pymysql. I have been debugging on my computer for two days, and I am sure this is the problem.

**Environment**
 - OS: window11 ubuntu20
 - Server and version: mysql8.0
 - PyMySQL version: 1.0.2

**Additional context**
Lost host after connecting to ssl
An error is reported on line 721 under the connections.py file

**Comment by canotf** [comment]
I can't wait for the official fix, I pulled the source code to fix it and have used it

**Comment by methane** [comment]
I can't understand what "Lost host after connecting to ssl" means.

The error seems just auth error.

**Comment by canotf** [comment]
> 我无法理解“连接到 ssl 后丢失的主机”是什么意思。
> 
> 该错误似乎只是身份验证错误。

I have repeated the debugging for three days and determined that it is not the account and database.  It seems that the error is caused by dbpool.  When I was debugging, I entered the connection pool and found that there was a way to disconnect it somehow after the connection. At present, it is very late in Beijing. I will send you the modified source code after dawn.

> I can't understand what "Lost host after connecting to ssl" means.
> 
> The error seems just auth error.

I have repeated the debugging for three days and determined that it is not the account and database.  It seems that the error is caused by dbpool.  When I was debugging, I entered the connection pool and found that there was a way to disconnect it somehow after the connection. At present, it is very late in Beijing. I will send you the modified source code after dawn.

**Comment by canotf** [comment]
> > 我无法理解“连接到 ssl 后丢失的主机”是什么英文。
> > 该错误似乎只是身份验证错误。
> 
> 我反复调试了三天，确定不是账号和数据库。该错误似乎是由 dbpool 引起的。调试的时候，进入连接池，发现连接后有办法断开连接。目前，北京已经很晚了。天亮后我将修改后的源代码发送给您。
> 
> > 我无法理解“连接到 ssl 后丢失的主机”是什么意思。
> > 该错误似乎只是身份验证错误。
> 
> 我反复调试了三天，确定不是账号和数据库。该错误似乎是由 dbpool 引起的。调试的时候，进入连接池，发现连接后有办法断开连接。目前，北京已经很晚了。天亮后我将修改后的源代码发送给您。



> 我无法理解“连接到 ssl 后丢失的主机”是什么意思。
> 
> 该错误似乎只是身份验证错误。

The version controller website I am using is our China Gitee.com, and the reply may not be timely. The fixed code URL is:https://gitee.com/aecode/aestate

**Comment by methane** [comment]
DBPool is not this project.
