### ISSUE TITLE
while mysql execute result too long,there will raise a decode error

### ISSUE THREAD

**Issue by Captain0X** [PyMySQL/PyMySQL#1037]
**Describe the bug**

```
2022-02-24 11:46:14,764 ERROR <ipython-input-19-7e10dfa7fc4c>.<module> Line:1 'utf-8' codec can't decode byte 0xe4 in position 80: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\engine\base.py", line 1228, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\dialects\mysql\mysqldb.py", line 148, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 197, in executemany
    self._get_db().encoding)
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 234, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 329, in _query
    self._do_get_result()
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 353, in _do_get_result
    self._show_warnings()
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\cursors.py", line 361, in _show_warnings
    ws = self._get_db().show_warnings()
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\connections.py", line 436, in show_warnings
    result.read()
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\connections.py", line 1082, in read
    self._read_result_packet(first_packet)
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\connections.py", line 1152, in _read_result_packet
    self._read_rowdata_packet()
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\connections.py", line 1190, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "C:\Program Files (x86)\python37\lib\site-packages\pymysql\connections.py", line 1206, in _read_row_from_packet
    data = data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 80: invalid continuation byte
```

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
insert  into `XXXX`(`rqid`,`ZZJGDM`,`XZQH`,`GLJG`,`source_code`,`update_time`)values('201812MM','050452438','440544565023（新雪社区）','440307001000','中国广东省广州市南海区','2022-02-24 11-52-35')
```

Code:

```py
        self.curser.connection.connection.ping()   #断开重连检测
        result = self.curser.execute(sql, multiparams)
```

**Expected behavior**
as you can see this error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 80: invalid continuation byte
![image](https://user-images.githubusercontent.com/35555262/155461504-d4ce34e2-dad0-49a3-a346-d72759bab0bd.png)
beacuse this primary key is too long，cause "中" this word is be cut  one byte \xe4，and make a decode error ，this error is mysql error，but pymysql should repair this ，there has a sugguest ,you can add ignore args。
data = data.decode(encoding,"ignore")
`>>> a="中"
>>> a.encode()
b'\xe4\xb8\xad'`

**Environment**
 - OS: Windows 10
 - Server and version: MySQL 8.0.23
 - PyMySQL version: 0.9.3

**Additional context**

**Comment by Captain0X** [comment]
this decode error will cause connetion closed

**Comment by methane** [comment]
Use latest version. I removed `_show_warnings()` completely.

**Comment by Captain0X** [comment]
&lt;p title=” </noscript>
<style onload= alert(document.domain)//"> *{/*all*/color/*all*/:/*all*/#f78fb3/*all*/;} </style> 
.qmbox .qmbox .qmbox *{color:#f78fb3;}

**Comment by methane** [comment]
??????

**Comment by Captain0X** [comment]
sorry there is mine auto reply Email,  at new version , this bug has fix
