### ISSUE TITLE
Random "NoSuchColumnError" exceptions thrown.

### ISSUE THREAD

**Issue by tuxtoti** [PyMySQL/PyMySQL#259]
I randomly get theses exceptions thrown for various tables even though I have these columns defined. 

```python
Traceback (most recent call last):
  File "/home/ops/recruiter-parichay/app/models/email_template.py", line 29, in get
    .filter_by(template_id= template_id, parichay_mail_template_id= 0).one()
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2361, in one
    ret = list(self)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    labels) for row in fetch]
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3469, in proc
    return row[column]
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 332, in _key_fallback
    expression._string_or_unprintable(key))
NoSuchColumnError: "Could not locate column in row for column 'email_template.template_name'"
```
I'm running PyMySQL==0.6.2 and SQLAlchemy==0.9.4 and Flask-SQLAlchemy==1.0 
I'm also using gevent==1.0.1 , if that matters.

**Comment by methane** [comment]
Close since long time without additional information.
