### ISSUE TITLE
RuntimeError: reentrant call inside <_io.BufferedReader> exception thrown

### ISSUE THREAD

**Issue by tuxtoti** [PyMySQL/PyMySQL#260]
```python

Traceback (most recent call last):
  File "/home/ops/recruiter-parichay/app/models/email_template.py", line 29, in get
    .filter_by(template_id= template_id, parichay_mail_template_id= 0).one()
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2361, in one
    ret = list(self)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2404, in __iter__
    return self._execute_and_instances(context)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2419, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1111, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 940, in _execute_context
    context)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/cursors.py", line 132, in execute
    result = self._query(query)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/cursors.py", line 271, in _query
    conn.query(q)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 726, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 861, in _read_query_result
    result.read()
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 1064, in read
    first_packet = self.connection._read_packet()
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 825, in _read_packet
    packet = packet_type(self)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 242, in __init__
File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 242, in __init__
    self._recv_packet(connection)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 248, in _recv_packet
    packet_header = connection._read_bytes(4)
  File "/home/ops/recruiter-parichay/ENV_RECP/local/lib/python2.7/site-packages/pymysql/connections.py", line 832, in _read_bytes
    data = self._rfile.read(num_bytes)
RuntimeError: reentrant call inside <_io.BufferedReader name=13>

````
Im running PyMySQL==0.6.2 and SQLAlchemy==0.9.4 and Flask-SQLAlchemy==1.0 
I'm also using gevent==1.0.1

**Comment by methane** [comment]
This issue has too few information.  It may be same to #275 or not.
No one can manage this issue until further information provided.

If enough information are added, please reopen.

**Comment by maicss** [comment]
this error happens to my code too. it looks like this problem still not resolve(need more information) .

my code depends:

- python 3.5.1
- requests
- gevent
- pymysql
- mysql
- lxml

the error is : 
```
Traceback (most recent call last):
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "let_us_rock2.py", line 66, in _write_link_to_db
    self.db.save_links(link)
  File "/Users/maic/Documents/py/py3/code/pa-zhihu/my_db.py", line 101, in save_links
    code = self.is_exist_link(link)
  File "/Users/maic/Documents/py/py3/code/pa-zhihu/my_db.py", line 123, in is_exist_link
    cor.execute(sql)
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/connections.py", line 835, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/connections.py", line 1019, in _read_query_result
    result.read()
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/connections.py", line 1302, in read
    first_packet = self.connection._read_packet()
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/connections.py", line 961, in _read_packet
    packet_header = self._read_bytes(4)
  File "/Users/maic/Documents/py/py3/lib/python3.5/site-packages/pymysql/connections.py", line 988, in _read_bytes
    data = self._rfile.read(num_bytes)
RuntimeError: reentrant call inside <_io.BufferedReader name=8>
<Greenlet at 0x10ef3b930: <bound method Slut._write_link_to_db of <__main__.Slut object at 0x10c816898>>> failed with RuntimeError
```

because i am a noob to python, and my English is not good as well, i cannot make sure describe the error clear. so i give you [my repository](https://github.com/maicWorkGithub/pa-zhihu), sorry for that......

**i even cannot ensure there is no syntax error.**

the main script is `let_us_rock3.py`.
and this script need a account for https://www.zhihu.com, and a cookies file for it. although i wrote the script to generate it, but i still not test it. so there are two ways to get it: first i give you mine(you give me your email), and you don't need create a account for the website, two you register for the website and use package 'zhihu-py3' to generate the cookies file.

this may be a big trouble for you, even you wont help, i still understand...

i am take some program to practice, so i use `sqlite` first, it works, and now i want try mysql...
`let_us_rock2` is sqlite and `let_us_rock3` is mysql

sorry for that, again.

**Comment by methane** [comment]
> because i am a noob to python,

I recommend you to stop using gevent.  It's a a "patch and pray" framework unless you understand all libraries you use deeply.

This problem can be happen when multiple greenlet uses same connection concurrently.
Unless you have confidence you did right thing, this exception means "Bad library usage", not "There are some bug in library".

I'm not free teacher or tech support.  Post a question to Q&A site like stackoverflow.  Not issue tracker.

**Comment by methane** [comment]
> and let_us_rock3 is mysql

There are no `let_us_rock3` in your repository.

When looking `let_us_rock2`, you use same db from multiple greenlet.  This is what you shouldn't do.

**Comment by maicss** [comment]
@methane i push again just now, the script is success commit.
i don't what exactly what you mean. the way i catch data is use multiple greenlet, if not use save data use gevent queue, what else can i do?

**Comment by maicss** [comment]
sorry, i did't saw you post above. got, thanks.

**Comment by ZonghaoWang** [comment]
sql command shoud be push to a gevent.queue
