### ISSUE TITLE
Test suite errors with MariaDB 5.1 and Python 2.7.5 

### ISSUE THREAD

**Issue by iainhouston** [PyMySQL/PyMySQL#264]
The two errors didn't look intentional so here's the failure report:
(PyMySQL version 0.6)

    $ mysql --version
    mysql  Ver 15.1 Distrib 10.0.12-MariaDB, for osx10.9 (i386) using readline 5.1
    iainhouston@leo:~/PyMySQL-PyMySQL-7c86923
    $ python --version
    Python 2.7.5
    iainhouston@leo:~/PyMySQL-PyMySQL-7c86923
    $ emacs pymysql/tests/databases.json
    iainhouston@leo:~/PyMySQL-PyMySQL-7c86923
    $ python runtests.py
    ............Set max_allowed_packet to bigger than 17MB
    .....F....................sE..x.....s...E......................................................x.......
    ======================================================================
    ERROR: test_issue_36 (pymysql.tests.test_issues.TestNewIssues)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/tests/test_issues.py", line 200, in test_issue_36
        conn.kill(kill_id)
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 748, in kill
        return self._read_ok_packet()
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 667, in _read_ok_packet
        pkt = self._read_packet()
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 827, in _read_packet
        packet.check_error()
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 374, in check_error
        raise_mysql_exception(self.__data)
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/err.py", line 117, in raise_mysql_exception
        _check_mysql_exception(errinfo)
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/err.py", line 113, in _check_mysql_exception
        raise InternalError(errno, errorvalue)
    InternalError: (1927, u'Connection was killed')

    ======================================================================
    ERROR: test_issue_6 (pymysql.tests.test_issues.TestOldIssues)
    exception: TypeError: ord() expected a character, but string of length 0 found
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/tests/test_issues.py", line 61, in test_issue_6
        conn = pymysql.connect(**kwargs)
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/__init__.py", line 88, in Connect
        return Connection(*args, **kwargs)
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 635, in __init__
        self._connect()
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/connections.py", line 819, in _connect
        2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
    OperationalError: (2003, 'Can\'t connect to MySQL server on u\'localhost\' ((1044, u"Access denied for user \'Django\'@\'localhost\' to database \'mysql\'"))')

    ======================================================================
    FAIL: test_datetime (pymysql.tests.test_basic.TestConversion)
    test conversion of null, empty string
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/iainhouston/PyMySQL-PyMySQL-7c86923/pymysql/tests/test_basic.py", line 113, in test_datetime
        c.fetchone())
    AssertionError: Tuples differ: (datetime.timedelta(0, 45000),... != (datetime.timedelta(0, 45000),...

    First differing element 2:
    23:12:59.051000
    23:12:59.005100

      (datetime.timedelta(0, 45000),
       datetime.timedelta(0, 83579),
    -  datetime.timedelta(0, 83579, 51000))
    ?                                   -

    +  datetime.timedelta(0, 83579, 5100))

    ----------------------------------------------------------------------
    Ran 115 tests in 11.068s

    FAILED (failures=1, errors=2, skipped=2, expected failures=2)

**Comment by methane** [comment]
I think all errors fixed in current master branch.
