### ISSUE TITLE
AttributeError: 'module' object has no attribute 'escape'

### ISSUE THREAD

**Issue by dnozay** [PyMySQL/PyMySQL#273]
Hi,
I am using `django` 1.7 and was trying to run migrations with `./manage.py sqlmigrate testruns 0002`, but it seems that `pymysql` is not a drop-in replacement for `MySQLdb` w.r.t. `.escape()`.

```
(tools)$ ./local_manage.py sqlmigrate testruns 0002 
Traceback (most recent call last):
  File "./local_manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/some_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/some_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/some_venv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/some_venv/lib/python2.7/site-packages/django/core/management/commands/sqlmigrate.py", line 30, in execute
    return super(Command, self).execute(*args, **options)
  File "/some_venv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/some_venv/lib/python2.7/site-packages/django/core/management/commands/sqlmigrate.py", line 61, in handle
    sql_statements = executor.collect_sql(plan)
  File "/some_venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 77, in collect_sql
    migration.apply(project_state, schema_editor, collect_sql=True)
  File "/some_venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/some_venv/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/some_venv/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 42, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/some_venv/lib/python2.7/site-packages/django/db/backends/schema.py", line 390, in add_field
    self.execute(sql, params)
  File "/some_venv/lib/python2.7/site-packages/django/db/backends/schema.py", line 96, in execute
    self.collected_sql.append((sql % tuple(map(self.quote_value, params))) + ";")
  File "/some_venv/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 32, in quote_value
    return MySQLdb.escape(value, MySQLdb.converters.conversions)
AttributeError: 'module' object has no attribute 'escape'
```

Here are my settings:

```
# settings.py
from pymysql import install_as_MySQLdb
install_as_MySQLdb()

DATABASES['localhost'] = {
    'ENGINE': 'django.db.backends.mysql',
    'HOST': 'localhost',
    'USER': 'django',
    'PASSWORD': 'django',
    'NAME': 'testdb',
}
```

**Comment by th0729** [comment]
Thanks!

**Comment by methane** [comment]
Could you file an issue to Django?
module level escape function must not be used since it doesn't know how to escape collectly.

It's like `mysql_escape` vs `mysql_real_escape` issue.

**Comment by cmehay** [comment]
This issue seems to still be here on 0.8.0 with django 2.0.2.

**Comment by methane** [comment]
I said "Could you file an issue to Django?"

Leaving comment here without reporting to Django is not helpful.
