### ISSUE TITLE
TypeError on warnings with BLOB field queries

### ISSUE THREAD

**Issue by conqp** [PyMySQL/PyMySQL#310]
I am getting TypeErrors when I try to save peewee.Model instances with blob fields and explicit connection handling:
```
CRITICAL ERROR: Unexpected exception while exporting to 1044003@OpenimmoDB
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/homie/core/retard.py", line 259, in __export
t.openimmo = data
File "/usr/local/lib/python3.4/dist-packages/homie/api/interface.py", line 354, in openimmo
if self._create(new):
File "/usr/local/lib/python3.4/dist-packages/homie/mods/openimmodb/interface.py", line 73, in _create
result = record.save() and result
File "/usr/local/lib/python3.4/dist-packages/peewee-2.4.7-py3.4.egg/peewee.py", line 3893, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "/usr/local/lib/python3.4/dist-packages/peewee-2.4.7-py3.4.egg/peewee.py", line 2688, in execute
return self.database.last_insert_id(self._execute(), self.model_class)
File "/usr/local/lib/python3.4/dist-packages/peewee-2.4.7-py3.4.egg/peewee.py", line 2243, in _execute
return self.database.execute_sql(sql, params, self.require_commit)
File "/usr/local/lib/python3.4/dist-packages/peewee-2.4.7-py3.4.egg/peewee.py", line 2872, in execute_sql
cursor.execute(sql, params or ())
File "/usr/local/lib/python3.4/dist-packages/PyMySQL-0.6.3-py3.4.egg/pymysql/cursors.py", line 127, in execute
result = self._query(query)
File "/usr/local/lib/python3.4/dist-packages/PyMySQL-0.6.3-py3.4.egg/pymysql/cursors.py", line 270, in _query
self._do_get_result()
File "/usr/local/lib/python3.4/dist-packages/PyMySQL-0.6.3-py3.4.egg/pymysql/cursors.py", line 285, in _do_get_result
self._show_warnings(conn)
File "/usr/local/lib/python3.4/dist-packages/PyMySQL-0.6.3-py3.4.egg/pymysql/cursors.py", line 290, in _show_warnings
warnings.warn(w[-1], err.Warning, 4)
TypeError: can't use a string pattern on a bytes-like object
```
This happens while saving records with blob fields within this method:
```
    def _create(self, real_estate):
        """Creates database records from a tuple
        of OpenImmo.immobilie and related records"""
        immobilie, related_records = real_estate
        result = True
        for record in chain([immobilie], related_records):
            with connection(record):
                result = record.save() and result
        return result
```

Where the method `connection()` does the following:

```
def connection(model):
    """Ensure that a database connection to the database
    of a peewee.Model is being established and closed.

    Usage:
        with connection(MyModel):
            for record in MyModel.select().where(True):
                pass

    Or:
        with connection(my_record):
            my_record.save()

    Or even:
        with connection(my_record):
            my_record.delete_instance()

    You got the idea...
    """

    return model._meta.database.execution_context()
```

The respective BLOB fields are of type `bytes`:

```
2015-02-19 13:53:44.917238 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 132782 bytes
2015-02-19 13:53:44.917408 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 145331 bytes
2015-02-19 13:53:44.917571 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 44042 bytes
2015-02-19 13:53:44.917707 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 48776 bytes
2015-02-19 13:53:44.917842 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 50758 bytes
2015-02-19 13:53:44.918012 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 55808 bytes
2015-02-19 13:53:44.918142 ESC[1mAnhaengeESC[0m ESC[0mESC[94mINFOESC[0m Setting data of type: <class 'bytes'> with length: 42520 bytes
```

Which is being logged when the respective module is created:
```
class Anhaenge(Factory):
    """Creates anhaenge entries"""

    def build(self, openimmo_obid, anhang):
        """Creates an anhenge entry"""
        if not anhang:
            return None
        result = openimmodb.Anhaenge()
        result.openimmo_obid = openimmo_obid
        result.location = location2id.get(anhang.location, 0)
        result.gruppe = gruppe2id.get(anhang.gruppe, 0)
        result.anhangtitel = self.x2str(anhang.anhangtitel, '')
        result.format = self.x2str(anhang.format, '')
        data = anhang.data
        self.logger.info(' '.join(['Setting data of type:', str(type(data)),
                                   'with length:', str(len(data)), 'bytes']))
        result.daten = data
        return result
```

My questions now are:
1) Why am I getting warnings anyway?
2) Why does the attempt to report those raise a `TypeError`

Thanks for looking into it and please notify me, if you need further information.

**Comment by methane** [comment]
May I have complete code to reproduce the problem?
I want to fix this issue before releasing next version, if it can be reproduced on current master branch.

**Comment by conqp** [comment]
The problem is that the respective software depends on four large custom-made packages in total.
So I will provide you with the respective database-ORM module and the database library below.
Furthermore I am using the latest version of peewee, which you can find here: https://github.com/coleifer/peewee
Database models (from package `homie.mods.openimmodb.openimmodb`):
```
"""Openimmo database models"""

from homeinfolib import improved

__author__ = 'Richard Neumann'
__date__ = '27.06.2014'
__all__ = ['AnbieterAnhaenge', 'Anbieter', 'AngeschlGastronomie', 'Anhaenge',
           'Ausblick', 'AusrichtBalkonTerrasse', 'Ausstattung', 'Bad',
           'Befeuerung', 'Boden', 'DistanzSsport', 'Distanz', 'Energieausweis',
           'Fahrstuhl', 'Flaeche', 'Freitexte', 'Geo', 'Geokoordinaten',
           'Heizungsart', 'Immobilie', 'Infrastruktur', 'Kontaktperson',
           'Kueche', 'Objektkategorie', 'Preise', 'Serviceleistungen',
           'Sicherheitstechnik', 'Stp', 'VerwaltungObjekt',
           'VerwaltungTechn', 'WeitereAdresse', 'ZustandAngaben']

from peewee import (Model, MySQLDatabase, PrimaryKeyField, CharField,
                    DateTimeField, TextField, IntegerField,
                    BlobField, BooleanField, DoubleField)

database = MySQLDatabase(None)


@improved
class OIDBModel(Model):
    """OpenimmoDB model"""

    class Meta():
        database = database


class AnbieterAnhaenge(OIDBModel):
    """Realtor attachments"""

    class Meta:
        db_table = 'anbieter_anhaenge'

    ID = PrimaryKeyField(10)
    openimmo_anid = CharField(255)
    location = IntegerField(10)
    gruppe = IntegerField(10)
    anhangtitel = CharField(255)
    format = CharField(255)
    daten = BlobField()
    pfad = CharField(255)


class Anbieter(OIDBModel):
    """Realtors"""

    class Meta:
        db_table = 'anbieter'

    ID = PrimaryKeyField(10)
    anbieternr = CharField(255)
    firma = TextField()
    openimmo_anid = CharField(255)


class AngeschlGastronomie(OIDBModel):
    """Connected gastronomy"""

    class Meta:
        db_table = 'angeschl_gastronomie'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_angeschl_gastronomie = IntegerField(10)


class Anhaenge(OIDBModel):
    """Attachments"""

    class Meta:
        db_table = 'anhaenge'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    location = IntegerField(10)
    gruppe = IntegerField(10)
    anhangtitel = CharField(255)
    format = CharField(255)
    daten = BlobField()
    pfad = CharField(255)
    imgnr = IntegerField(2)
    imgtype = CharField(20)
    sizex = CharField(20)
    sizey = CharField(20)
    createtime = DateTimeField()
    Link = CharField(255)


class Ausblick(OIDBModel):
    """View"""

    class Meta:
        db_table = 'ausblick'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_ausblick = IntegerField(10)


class AusrichtBalkonTerrasse(OIDBModel):
    """Orientation balcony or porch"""

    class Meta:
        db_table = 'ausricht_balkon_terrasse'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausricht_b_t = IntegerField(10)


class Ausstattung(OIDBModel):
    """Features"""

    class Meta:
        db_table = 'ausstattung'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    wg_geeignet = BooleanField()
    raeume_veraenderbar = BooleanField()
    kamin = BooleanField()
    klimatisiert = BooleanField()
    stellplatzart = BooleanField()
    gartennutzung = BooleanField()
    _moebliert = CharField(4, db_column='moebliert')    # XXX: Enum here
    _moebliert_values = ['', 'NEIN', 'TEIL', 'VOLL']
    rollstuhlgerecht = BooleanField()
    kabel_sat_tv = BooleanField()
    barrierefrei = BooleanField()
    sauna = BooleanField()
    swimmingpool = BooleanField()
    wash_trockenraum = BooleanField()
    dv_verkabelung = BooleanField()
    rampe = BooleanField()
    hebebuehne = BooleanField()
    kran = BooleanField()
    gastterrasse = BooleanField()
    stromanschlusswert = BooleanField()
    kantine_cafetaria = BooleanField()  # XXX: Typo in openimmoDB
    teekueche = BooleanField()
    brauereibindung = BooleanField()
    sporteinrichtungen = BooleanField()
    wellnessbereich = BooleanField()
    telefon_ferienimmobilie = BooleanField()
    unterkellert = BooleanField()

    @property
    def moebliert(self):
        """Simulate enum access"""
        return self._moebliert

    @moebliert.setter
    def moebliert(self, moebliert):
        """Simulate enum access"""
        if moebliert in self._moebliert_values:
            self._moebliert = moebliert
        else:
            try:
                moebliert = int(moebliert)
            except:
                raise ValueError(' '.join(['"moebliert" must be one of',
                                           str(self._moebliert_values),
                                           'but', '"' + str(moebliert) + '"',
                                           'was given']))
            else:
                self._moebliert = self._moebliert_values[moebliert]

    @property
    def kantine_cafeteria(self):
        """Correction of typo 'kantine_cafetaria'"""
        return self.kantine_cafetaria

    @kantine_cafeteria.setter
    def kantine_cafeteria(self, kantine_cafeteria):
        """Correction of typo 'kantine_cafetaria'"""
        self.kantine_cafetaria = kantine_cafeteria


class Bad(OIDBModel):
    """Bathroom"""

    class Meta:
        db_table = 'bad'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_bad = IntegerField(10)


class Befeuerung(OIDBModel):
    """Firing"""

    class Meta:
        db_table = 'befeuerung'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_befeuerung = IntegerField(10)


class Boden(OIDBModel):
    """Floor"""

    class Meta:
        db_table = 'boden'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_boden = IntegerField(10)


class DistanzSport(OIDBModel):
    """Distance for sport"""

    class Meta:
        db_table = 'distanz_sport'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_distanz_sport = IntegerField(10)
    distanz = CharField(255)
    bemerkung = TextField()


class Distanz(OIDBModel):
    """Distance"""

    class Meta:
        db_table = 'distanz'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_distanz = IntegerField(10)
    distanz = CharField(255)
    bemerkung = TextField()


class Energieausweis(OIDBModel):
    """Energy performance certificate"""

    class Meta:
        db_table = 'energieausweis'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    energieausweis = CharField(32)
    wert = DoubleField()
    energietraeger = TextField()
    baujahr = IntegerField(11)
    effizienzklasse = TextField()
    waerme = DoubleField()
    strom = DoubleField()


class Fahrstuhl(OIDBModel):
    """Lift"""

    class Meta:
        db_table = 'fahrstuhl'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_fahrstuhl = IntegerField(10)


class Flaeche(OIDBModel):
    """Area / space"""

    class Meta:
        db_table = 'flaeche'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    wohnflaeche = CharField(255)
    nutzflaeche = CharField(255)
    gesamtflaeche = CharField(255)
    ladenflaeche = CharField(255)
    lagerflaeche = CharField(255)
    verkaufsflaeche = CharField(255)
    freiflaeche = CharField(255)
    bueroflaeche = CharField(255)
    bueroteilflaeche = CharField(255)
    fensterfront = CharField(255)
    verwaltungsflaeche = CharField(255)
    gastroflaeche = CharField(255)
    grz = CharField(255)
    gfz = CharField(255)
    bmz = CharField(255)
    bgf = CharField(255)
    grundstuecksflaeche = CharField(255)
    sonstflaeche = CharField(255)
    anzahl_zimmer = CharField(255)
    anzahl_schlafzimmer = CharField(255)
    anzahl_badezimmer = CharField(255)
    anzahl_sep_wc = CharField(255)
    anzahl_balkon_terrassen = CharField(255)
    balkon_terrasse_flaeche = CharField(255)
    anzahl_wohn_schlafzimmer = CharField(255)
    gartenflaeche = CharField(255)
    kellerflaeche = CharField(255)
    fensterfront_qm = CharField(255)
    grundstuecksfront = CharField(255)
    dachbodenflaeche = CharField(255)
    teilbar_ab = CharField(255)
    beheizbare_flaeche = CharField(255)
    anzahl_stellplaetze = CharField(255)
    plaetze_gastraum = CharField(255)
    anzahl_betten = CharField(255)
    anzahl_tagungsraeume = CharField(255)
    vermietbare_flaeche = CharField(255)
    anzahl_wohneinheiten = CharField(255)
    anzahl_gewerbeeinheiten = CharField(255)
    einliegerwohnung = CharField(255)


class Freitexte(OIDBModel):
    """Free texts"""

    class Meta:
        db_table = 'freitexte'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    objekttitel = TextField()
    dreizeiler = TextField()
    lage = TextField()
    ausstatt_beschr = TextField()
    objektbeschreibung = TextField()
    sonstige_angaben = TextField()
    printzeile = TextField()


class Geo(OIDBModel):
    """Geo data"""

    class Meta:
        db_table = 'geo'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    plz = CharField(10)
    ort = CharField(255)
    strasse = CharField(255)
    hausnummer = CharField(10)
    bundesland = CharField(255)
    land = CharField(10)
    gemeindecode = CharField(255)
    flur = CharField(255)
    flurstueck = CharField(255)
    gemarkung = CharField(255)
    etage = CharField(255)
    lage_im_bau = IntegerField(10)
    wohnungsnr = CharField(255)
    lage_gebiet = IntegerField(10)
    regionaler_zusatz = CharField(255)


class Geokoordinaten(OIDBModel):
    """Geo coordinates"""

    class Meta:
        db_table = 'geokoordinaten'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    breitengrad = CharField(255)
    laengengrad = CharField(255)
    land = CharField(255)
    bundesland = CharField(255)
    region = CharField(255)
    plz = CharField(255)
    stadt = CharField(255)
    strasse = CharField(255)
    hausnummer = CharField(255)
    accuracy = CharField(4)
    request = CharField(255)


class Heizungsart(OIDBModel):
    """Heating type"""

    class Meta:
        db_table = 'heizungsart'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_heizung = IntegerField(10)


class Immobilie(OIDBModel):
    """Real estate basic data"""

    class Meta:
        db_table = 'immobilie'

    ID = PrimaryKeyField(10)
    openimmo_anid = CharField(255)
    openimmo_obid = CharField(255)
    objektnr_intern = CharField(255)
    objektnr_extern = CharField(255)
    Status = CharField(15)
    Time = CharField(255)
    Time2 = CharField(255)


class Infrastruktur(OIDBModel):
    """Infrastructure"""

    class Meta:
        db_table = 'infrastruktur'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    zulieferung = CharField(255)


class Kontaktperson(OIDBModel):
    """Realtor contact"""

    class Meta:
        db_table = 'kontaktperson'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    email_zentrale = CharField(255)
    email_direkt = CharField(255)
    email_sonstige = CharField(255)
    tel_zentrale = CharField(255)
    tel_durchw = CharField(255)
    tel_fax = CharField(255)
    tel_handy = CharField(255)
    tel_sonstige = CharField(255)
    name = CharField(255)
    vorname = CharField(255)
    titel = CharField(255)
    anrede = CharField(255)
    anrede_brief = CharField(255)
    firma = CharField(255)
    zusatzfeld = CharField(255)
    strasse = CharField(255)
    hausnummer = CharField(255)
    plz = CharField(255)
    ort = CharField(255)
    postfach = CharField(255)
    postf_plz = CharField(255)
    postf_ort = CharField(255)
    land = IntegerField(10)
    email_privat = CharField(255)
    tel_privat = CharField(255)
    url = CharField(255)
    adressfreigabe = CharField(255)
    personennummer = CharField(255)
    freitextfeld = CharField(255)


class Kueche(OIDBModel):
    """Kitchen"""

    class Meta:
        db_table = 'kueche'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_kueche = IntegerField(10)


class Objektkategorie(OIDBModel):
    """Object category"""

    class Meta:
        db_table = 'objektkategorie'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    nutzungsart = IntegerField(10)
    vermarktungsart = IntegerField(10)
    objektart = IntegerField(10)


class Preise(OIDBModel):
    """Prices"""

    class Meta:
        db_table = 'preise'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    kaufpreis = CharField(255)
    nettokaltmiete = CharField(255)
    kaltmiete = CharField(255)
    warmmiete = CharField(255)
    nebenkosten = CharField(255)
    heizkosten = CharField(255)
    zzgl_mehrwertsteuer = CharField(255)
    mietzuschlaege = CharField(255)
    pacht = CharField(255)
    erbpacht = CharField(255)
    hausgeld = CharField(255)
    preis_zeitraum_von = CharField(255)
    preis_zeitraum_bis = CharField(255)
    preis_zeiteinheit = CharField(255)  # TODO: Need set here
    mietpreis_pro_qm = CharField(255)
    kaufpreis_pro_qm = CharField(255)
    innen_courtage = CharField(255)
    innen_courtage_mwst = CharField(255)
    aussen_courtage = CharField(255)
    aussen_courtage_mwst = CharField(255)
    weahrung = IntegerField(10)  # XXX: Typo in openimmoDB
    mwst_satz = CharField(255)
    freitext_preis = CharField(255)
    x_fache = CharField(255)
    nettorendite = CharField(255)
    mieteinnahmen_ist = CharField(255)
    mieteinnahmen_soll = CharField(255)
    erschliessungskosten = CharField(255)
    kaution = CharField(255)
    geschaeftsguthaben = CharField(255)

    @property
    def waehrung(self):
        """Correction of typo 'weahrung'"""
        return self.weahrung

    @waehrung.setter
    def waehrung(self, waehrung):
        """Correction of typo 'weahrung'"""
        self.weahrung = waehrung


class Serviceleistungen(OIDBModel):
    """Services"""

    class Meta:
        db_table = 'serviceleistungen'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_serviceleistungen = IntegerField(10)


class Sicherheitstechnik(OIDBModel):
    """Security technology"""

    class Meta:
        db_table = 'sicherheitstechnik'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    ausstatt_sicherheitstechnik = IntegerField(10)


class Stp(OIDBModel):
    """Parking lots"""

    class Meta:
        db_table = 'stp'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    stellplatzmiete = CharField(255)
    stellplatzkaufpreis = CharField(255)
    anzahl = CharField(255)
    stp_typ = IntegerField(10)
    bemerkung = CharField(255)


class VerwaltungObjekt(OIDBModel):
    """Object administration"""

    class Meta:
        db_table = 'verwaltung_objekt'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    objektadresse_freigeben = IntegerField(1)
    verfuegbar_ab = CharField(255)
    abdatum = CharField(255)
    bisdatum = CharField(255)
    min_mietdauer = CharField(255)
    max_mietdauer = CharField(255)
    versteigerungstermin = CharField(255)
    wbs_sozialwohnung = IntegerField(1)
    vermietet = IntegerField(1)
    gruppennummer = CharField(255)
    zugang = CharField(255)
    laufzeit = CharField(255)
    max_personen = CharField(255)
    nichtraucher = IntegerField(1)
    haustiere = IntegerField(1)
    geschlecht = CharField(255)
    denkmalgeschuetzt = IntegerField(1)
    als_ferien = IntegerField(1)
    gewerbliche_nutzung = IntegerField(1)
    branchen = CharField(255)
    hochhaus = IntegerField(1)


class VerwaltungTechn(OIDBModel):
    """Technical administration"""

    class Meta:
        db_table = 'verwaltung_techn'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    objektnr_intern = CharField(255)
    objektnr_extern = CharField(255)
    aktion = CharField(255)
    aktiv_von = CharField(255)
    aktiv_bis = CharField(255)
    kennung_ursprung = CharField(255)
    stand_vom = CharField(255)
    weitergabe_generell = CharField(255)
    weitergabe_positiv = CharField(255)
    weitergabe_negativ = CharField(255)


class WeitereAdresse(OIDBModel):
    """Further address"""

    class Meta:
        db_table = 'weitere_adresse'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    adressart = CharField(255)
    vorname = CharField(255)
    name = CharField(255)
    titel = CharField(255)
    anrede = CharField(255)
    anrede_brief = CharField(255)
    firma = CharField(255)
    zusatzfeld = CharField(255)
    strasse = CharField(255)
    hausnummer = CharField(255)
    plz = CharField(255)
    ort = CharField(255)
    postfach = CharField(255)
    postf_plz = CharField(255)
    postf_ort = CharField(255)
    land = IntegerField(10)
    email_zentrale = CharField(255)
    email_direkt = CharField(255)
    email_privat = CharField(255)
    email_sonstige = CharField(255)
    tel_durchw = CharField(255)
    tel_zentrale = CharField(255)
    tel_handy = CharField(255)
    tel_fax = CharField(255)
    tel_privat = CharField(255)
    tel_sonstige = CharField(255)
    url = CharField(255)
    adressfreigabe = CharField(255)
    freitextfeld = CharField(255)


class ZustandAngaben(OIDBModel):
    """State data"""

    class Meta:
        db_table = 'zustand_angaben'

    ID = PrimaryKeyField(10)
    openimmo_obid = CharField(255)
    baujahr = CharField(255)
    zustand = IntegerField(10)
    baualter = CharField(255)
    bebaubar_nach = IntegerField(10)
    erschliessung = IntegerField(10)
    altlasten = CharField(255)


obid = [Immobilie, AngeschlGastronomie, Anhaenge,
        Ausblick, AusrichtBalkonTerrasse, Ausstattung, Bad,
        Befeuerung, Boden, DistanzSport, Distanz, Energieausweis,
        Fahrstuhl, Flaeche, Freitexte, Geo, Geokoordinaten,
        Heizungsart, Infrastruktur, Kontaktperson,
        Kueche, Objektkategorie, Preise, Serviceleistungen,
        Sicherheitstechnik, Stp, VerwaltungObjekt,
        VerwaltungTechn, WeitereAdresse, ZustandAngaben]
"""All openimmo_obid related tables"""

anid = [Anbieter, AnbieterAnhaenge]
"""All openimmo_anid related tables"""

```

And the database part of the `homeinfolib` (`homeinfolib.db`) used by the aforementioned module:

```
"""HOMEINFO general database library"""

__date__ = '12.01.2015'
__author__ = 'Richard Neumann'
__all__ = ['create', 'improved', 'connection']


def connection(model):
    """Ensure that a database connection to the database
    of a peewee.Model is being established and closed.

    Usage:
        with connection(MyModel):
            for record in MyModel.select().where(True):
                pass

    Or:
        with connection(my_record):
            my_record.save()

    Or even:
        with connection(my_record):
            my_record.delete_instance()

    You got the idea...
    """

    return model._meta.database.execution_context()


def create(model):
    """Decorator for peewee.Model definitions that
    actually should be created on load.

    Usage:
        @create
        class MyModel(peewee.Model):
            pass
    """

    with connection(model):
        model.create_table(fail_silently=True)
    return model


def improved(model):
    """Equips a model with useful improvements"""

    return model    # XXX: Pass for now
```

This should actually suffice, since the problem occurs, when saving instances of  the `Anhaenge` model containing binary data within the `daten` BLOB field. I am using a local MySQL database (mariadb) with InnoDB as engine.

**Comment by conqp** [comment]
Strike the last sentence. The DB engine is `MyISAM`.

**Comment by methane** [comment]
@conqp What message shown when applying #319 ?
