### ISSUE TITLE
Error in `escape_string` function if `value` in a numpy float

### ISSUE THREAD

**Issue by ostrokach** [PyMySQL/PyMySQL#324]
I get an error when I run a program which uses the sqlalchemy orm using the `PyMySQL` driver. Everything works without a problem using the `MySQLDB` driver. However, I need to make my code compatible with both Python 2  and 3, and `MySQLDB` does not support Python 3 (yet?).

The error I get is:

    TypeError: buffer size mismatch
    
The full traceback is attached at the end of the message.

The error arrises because the `escape_string()` function gets called with a `value` of type `numpy float64`. In the sqlalchemy orm, the field corresponding to that value is of type `Float`, so I am not sure why it would ever be processed with the `escape_string` function. 

Casting the value as a string solves the problem:

    def escape_string(value, mapping=None):
        return ("%s" % (ESCAPE_REGEX.sub(
                lambda match: ESCAPE_MAP.get(match.group(0)), str(value)),))
                                                              ^ cast as string

However, there's probably a deeper reason behind the bug, since `escape_string` probably shouldn't be called on a float anyway.

I get the same error in both Python 2.7 and Python 3.4. I am using the Anaconda distribution running on Ubuntu 14.04, PyMySQL version 0.6.6 that comes with conda. 

Traceback (most recent call last):

    File "<stdin>", line 1, in <module>
    File "/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
    File "/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)
    File "/working/elaspic/elaspic.py", line 87, in <module>
    uniprot_domains_and_domain_pairs = pipeline(uniprot_ids[0], mutations, run_type, n_cores)
    File "elaspic/pipeline.py", line 234, in __call__
    File "elaspic/pipeline.py", line 516, in _compute_mutations
    File "elaspic/sql_db.py", line 1103, in merge_mutation
    File "elaspic/sql_db.py", line 1029, in merge_row
    File "/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
    File "elaspic/sql_db.py", line 679, in session_scope
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 721, in commit
    self.transaction.commit()
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 354, in commit
    self._prepare_impl()
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 334, in _prepare_impl
    self.session.flush()
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1936, in _flush
    transaction.rollback(_capture_exception=True)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 58, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1900, in _flush
    flush_context.execute()
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 541, in _emit_insert_statements
    execute(statement, multiparams)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1027, in _handle_dbapi_exception
    util.reraise(*exc_info)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
    File "/anaconda/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
    File "/anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 132, in execute
    query = query % self._escape_args(args, conn)
    File "/anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 98, in _escape_args
    return tuple(conn.escape(arg) for arg in args)
    File "/anaconda/lib/python2.7/site-packages/pymysql/cursors.py", line 98, in <genexpr>
    return tuple(conn.escape(arg) for arg in args)
    File "/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 729, in escape
    return escape_item(obj, self.charset, mapping=mapping)
    File "/anaconda/lib/python2.7/site-packages/pymysql/converters.py", line 33, in escape_item
    val = encoder(val, mapping)
    File "/anaconda/lib/python2.7/site-packages/pymysql/converters.py", line 76, in escape_unicode
    return escape_str(value, mapping)
    File "/anaconda/lib/python2.7/site-packages/pymysql/converters.py", line 73, in escape_str
    return "'%s'" % escape_string(value, mapping)
    File "/anaconda/lib/python2.7/site-packages/pymysql/converters.py", line 70, in escape_string
    lambda match: ESCAPE_MAP.get(match.group(0)), value),))
    TypeError: buffer size mismatch

**Comment by methane** [comment]
> However, I need to make my code compatible with both Python 2 and 3, and MySQLDB does not support Python 3 (yet?).

Yes. MySQLdb development has been suspended for years.
You can use my fork of MySQLdb, named [mysqlclient](https://pypi.python.org/pypi/mysqlclient).
It support Python 3.

**Comment by methane** [comment]
> The error arrises because the escape_string() function gets called with a value of type numpy float64. In the sqlalchemy orm, the field corresponding to that value is of type Float, so I am not sure why it would ever be processed with the escape_string function.

escape functions are not related to column type defined by SQLAlchemy.
They are called by argument type. So there are no surprise for `escape_string()` is called for `numpy.float`.

```python
In [2]: f = numpy.float(3.14)

In [3]: str(f)
Out[3]: '3.14'
```

I don't know why `str()` is bad for you.

**Comment by ostrokach** [comment]
I added the `str()` cast myself. The original `escape_string()` function is as follows:

    def escape_string(value, mapping=None):
        return ("%s" % (ESCAPE_REGEX.sub(
                lambda match: ESCAPE_MAP.get(match.group(0)), value),))

So from I understand, the function tries to remove whitespace characters described by `ESCAPE_MAP` from a `numpy float`. This correctly gives the error:

    TypeError: can't use a string pattern on a bytes-like object

I added the `str()` cast myself, and that made everything work ok.

**Comment by ostrokach** [comment]
My code runs without errors when using `mysqlclient`. Thanks a lot for the suggestion!

**Comment by ei-grad** [comment]
Got the same issue. Moved to mysqlclient.
