### ISSUE TITLE
Connection to local MySQL fails on Google AppEngine SDK

### ISSUE THREAD

**Issue by riturajtiwari** [PyMySQL/PyMySQL#340]
I am using PyMySQL within Flask/SQLAlchemy on Google App Engine Dev App Server. My code sets up the DB connection string as:
```
'mysql+pymysql://myproject:myproject@localhost/myproject'
```
This fails with the following traceback. The final place is in `_socketio.py`'s `readinto` method. The raised exception does not seem to have any args.

```
Traceback (most recent call last):
  File "/Users/myuserid/Documents/Development/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/myuserid/Documents/Development/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/myuserid/Documents/Development/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/myuserid/Documents/Development/myapp-server/main.py", line 9, in <module>
    db.create_all()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/flask_sqlalchemy/__init__.py", line 895, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/myuserid/Documents/Development/myapp-server/lib/flask_sqlalchemy/__init__.py", line 887, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/sql/schema.py", line 3614, in create_all
    tables=tables)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/base.py", line 1850, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/base.py", line 1843, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/base.py", line 2034, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/base.py", line 2069, in _wrap_pool_connect
    return fn()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 708, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 1049, in _do_get
    self._dec_overflow()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 1046, in _do_get
    return self._create_connection()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/pool.py", line 602, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/connections.py", line 837, in _connect
    self._get_server_information()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/connections.py", line 1048, in _get_server_information
    packet = self._read_packet()
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/connections.py", line 882, in _read_packet
    packet_header = self._read_bytes(4)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/connections.py", line 899, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/Users/myuserid/Documents/Development/myapp-server/lib/pymysql/_socketio.py", line 64, in readinto
    n = e.args[0]
IndexError: tuple index out of range
INFO     2015-05-05 23:30:40,803 module.py:788] default: "GET / HTTP/1.1" 500 -
```

**Comment by riturajtiwari** [comment]
Editing the `_socketio.py` code to handle the case where the error has no args, now produces the following error:
```
connections.py", line 906, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
OperationalError: <unprintable OperationalError object>
```

**Comment by nik045** [comment]
:+1:

**Comment by methane** [comment]
@riturajtiwari Could you try replace line 906 in _read_bytes with "raise" ?

**Comment by jimktrains** [comment]
For anyone else looking for more information, the error being raised for me is: <class 'google.appengine.api.remote_socket._remote_socket.SocketApiNotImplementedError'>

So, it not being a mysql error may be part of the problem.

**Comment by methane** [comment]
How about this?
https://cloud.google.com/appengine/docs/python/sockets/

**Comment by jimktrains** [comment]
`recv_into` doesn't appear to be supported in appengine (https://code.google.com/p/appengine-devappserver2-experiment/source/browse/google/appengine/api/remote_socket/_remote_socket.py#847) (I can't seem to find the non experimental, but the version on my is the same except for the class being raised is `SocketApiNotImplementedError` not just `NotImplementedError`

**Comment by methane** [comment]
I found Google recommends MySQLdb.  Why don't you use MySQLdb?
https://cloud.google.com/appengine/docs/python/cloud-sql/

**Comment by makkasi** [comment]
OK, For everyone that finds this post as last hope to run it's project , what helps it's  to install latest version of Google app engine Python SDK. ( in my case 1.9.36)

**Comment by methane** [comment]
@makkasi Sorry, I can't understand your English sentence.  (I can read easy English grammer only.)
Do you mean Google AppEngine SDK 1.9.36 solves the issue?

**Comment by makkasi** [comment]
yes. It solves it for me. My English is little bit Joda English , but you got it right

**Comment by methane** [comment]
Thanks!
