### ISSUE TITLE
TypeError for multiple queries when one raises a warning

### ISSUE THREAD

**Issue by graingert** [PyMySQL/PyMySQL#343]
With the code:

```python
proc = """DROP PROCEDURE IF EXISTS get_testdb;
CREATE PROCEDURE get_testdb ()

BEGIN
     SELECT * FROM test_procedure;
END"""
cur = connection.cursor()
cur.execute(proc)
```
If DROP PROCEDURE raises a warning (when `get_testdb` does not exist) I get a type error:
```pytb
Traceback (most recent call last):
  File "/home/travis/build/graingert/pandas/pandas/io/tests/test_sql.py", line 1497, in test_read_procedure
    cursor.execute(proc)
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/pymysql/cursors.py", line 283, in _query
    self._do_get_result()
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/pymysql/cursors.py", line 298, in _do_get_result
    self._show_warnings(conn)
  File "/home/travis/miniconda/envs/pandas/lib/python2.7/site-packages/pymysql/cursors.py", line 302, in _show_warnings
    for w in ws:
TypeError: 'NoneType' object is not iterable
```

see https://github.com/pydata/pandas/pull/10105

**Comment by jorisvandenbossche** [comment]
I think there is already a PR for this: #333
