### ISSUE TITLE
AttributeError: 'module' object has no attribute 'install_as_MySQLdb'

### ISSUE THREAD

**Issue by cestq** [PyMySQL/PyMySQL#349]
I have a issue with django

I have done :
```
  pip install pymysql
```

 input 
`__init__.py`:
```
import pymysql
pymysql.install_as_MySQLdb()
```

settings.py:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'iat1',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
'autocommit': True,
},
```

and python manage.py syncdb  
 all  success  but then  python django runsever:
pymysql.install_as_MySQLdb()
AttributeError: 'module' object has no attribute 'install_as_MySQLdb'

how can I deal with this problem?
thx

**Comment by methane** [comment]
Add this line to your `__init__.py`:

```python
import pymysql
print(pymysql.__file__)
pymysql.install_as_MySQLdb()
```

**Comment by cestq** [comment]
Traceback (most recent call last):
  File "C:/1/cest/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 48, in __getattr__
    self._setup(name)
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\1\cest\cest_blog\__init__.py", line 2, in <module>
    print(pymysql.__file__)
AttributeError: 'module' object has no attribute '__file__'

**Comment by methane** [comment]
Django makes it difficult to distinguish problem.
http://stackoverflow.com/questions/12540257/django-module-object-has-no-attribute-file

I'm not familiar to Django.
How about putting `import pymysql; pymysql.install_as_MySQLdb()` to top of `manage.py` and your wsgi file instead of your package's `__init__`?

**Comment by cestq** [comment]
It still doesn't work and I putting those code to top of settings.py too:https://github.com/PyMySQL/PyMySQL/issues/273

"C:\Program Files\JetBrains\PyCharm\bin\runnerw.exe" C:\Python34\python.exe C:/1/cest/manage.py runserver 8000
Traceback (most recent call last):
  File "C:/1/cest/manage.py", line 2, in <module>
    import pymysql; pymysql.install_as_MySQLdb()
AttributeError: 'module' object has no attribute 'install_as_MySQLdb'

**Comment by methane** [comment]
Isn't `pymysq.__file__` too?
How about `print(pymysql)`?

**Comment by cestq** [comment]
>>> print(pymysql)
<module 'pymysql' from 'C:\\Python34\\lib\\site-packages\\pymysql\\__init__.py'>

**Comment by methane** [comment]
OK. Could you upload `C:\\Python34\\lib\\site-packages\\pymysql\\__init__.py` to gist, or zipped
`C:\\Python34\\lib\\site-packages\\pymysql` directory to somewhere?

**Comment by cestq** [comment]
there isn't __init__.py, in  C:\\Python34\\lib\\site-packages\\pymysql\\   I new-built one。I zipped to http://1drv.ms/1Nd0v0n

**Comment by methane** [comment]
OK, your PyMySQL is broken. remove the directory and reinstall via:
`pip install -U --force-reinstall pymysql`.

BTW, I recommend you to use [venv](https://docs.python.org/3/library/venv.html) to keep your environment clean.

**Comment by cestq** [comment]
Thank you very much , I reinstall pymysql then it's work.  I'll use venv  thx

**Comment by changyiru-code** [comment]
I have C:\\Python34\\lib\\site-packages\\pymysql\\__init__.py,but still AttributeError: 'module' object has no attribute 'install_as_MySQLdb',please ask what should i do?
