### ISSUE TITLE
error 2013/104 during initial connection

### ISSUE THREAD

**Issue by drsmith-wisc** [PyMySQL/PyMySQL#381]
Hello,

I'm attempting to connect to a mysql server, and pymysql throws error 2013 during the initial connection.  It appears the mysql server error is 104, and the failure occurs during the operation Connection._rfile.read(4) inside Connection._read_bytes().  The environment, traceback, and modified lines from connections.py are shown below.  Can you help me understand why Connection._read_bytes() throws IOError during the initial connection?  Is it an error on the pymysql side or the mysql server side?

Thanks,
Dave

```py
>>> import sys
>>> sys.version
'2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:50:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

>>> import pymysql
>>> pymysql.VERSION
(0, 6, 6, None)

>>> connection = pymysql.connect(host='*************',
...     user='*********',
...     passwd='**************',
...     db='*******',
...     port=*****)

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 644, in __init__
    self._connect()
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 837, in _connect
    self._get_server_information()
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 1054, in _get_server_information
    packet = self._read_packet()
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 882, in _read_packet
    packet_header = self._read_bytes(4)
  File "/p/fdf/anaconda/lib/python2.7/site-packages/pymysql/connections.py", line 906, in _read_bytes
    "IOError: Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'IOError: Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')
>>> 
```

Here are the relevant lines from Connection._read_bytes(), which I modified for debugging:

```py
    def _read_bytes(self, num_bytes):
        while True:
            try:
                data = self._rfile.read(num_bytes)
                break
            except IOError as e:
                if e.errno == errno.EINTR:
                    continue
                raise err.OperationalError(
                    2013,
                    "IOError: Lost connection to MySQL server during query (%s)" % (e,))
            except OSError as e:
                if e.errno == errno.EINTR:
                    continue
                raise err.OperationalError(
                    2013,
                    "OSError: Lost connection to MySQL server during query (%s)" % (e,))
```

**Comment by methane** [comment]
Server side.  Your server doesn't accept new connection.
If there are no messages in MySQL's error log, it may be problem of OS setup.
