### ISSUE TITLE
"Got packets out of order" error on large INSERT operation.

### ISSUE THREAD

**Issue by John-Nagle** [PyMySQL/PyMySQL#382]
Another problem associated with large transactions.

    ERROR: (1156, 'Got packets out of order')
    Traceback:
    Traceback (most recent call last):
    File "/var/www/sitetruth/public_html/cgi/sitetruth/InfoSite.py", line 609, in updatesiteinfo
        siteinfo.dbinsertall(db) # save into database
    File "/var/www/sitetruth/public_html/cgi/sitetruth/InfoSite.py", line 358, in dbinsertall
        self.dbinsertsections(cursor, self.ratingid, sections) # insert sections
    File "/var/www/sitetruth/public_html/cgi/sitetruth/InfoSite.py", line 337, in dbinsertsections
        section.dbinsert(dbcursor, rating_id, section_sequence, self.requesteddomain)
    File "/var/www/sitetruth/public_html/cgi/sitetruth/InfoSiteSection.py", line 56, in dbinsert
        dbcursor.execute(cmd, values) # do it
    File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 134, in execute
        result = self._query(query)
    File "/usr/local/lib/python3.4/site-packages/pymysql/cursors.py", line 282, in _query
        conn.query(q)
    File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 768, in query
        self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 929, in _read_query_result
        result.read()
    File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 1125, in read
        first_packet = self.connection._read_packet()
    File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 893, in _read_packet
        packet.check_error()
    File "/usr/local/lib/python3.4/site-packages/pymysql/connections.py", line 369, in check_error
        err.raise_mysql_exception(self._data)
    File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
        _check_mysql_exception(errinfo)
    File "/usr/local/lib/python3.4/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
        raise errorclass(errno, errorvalue)
    pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual  that corresponds to your MariaDB server version for the right syntax to use near \'\'<span      class=\\"detailsheading\\">Examined 10 relevant web pages in 24.5 seconds.<\' at line 4')

The code being executed is a big INSERT, with a huge block of XHTML. This code works fine for small requests, but this one happened to be far larger than usual.  The SQL statement is a constant; only the values change.

    cmd = """INSERT INTO sitesection 
		(rating_id, section_sequence, domain,
		section_title, summary_xhtml, details_xhtml, version)
		VALUES (%s,%s,%s,%s,%s,%s,%s)"""
		values = (rating_id, section_sequence, domain, 
			self.get_display_name(), self.get_summary_as_xhtml(), self.get_details_as_xhtml(), version)
		dbcursor.execute(cmd, values)	

This error has occurred with both MySQL and MariaDB on Linux, but isn't happening on Windows 7.

Versions (Linux): 
    PyMySQL (0.6.6)
    mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1
    CentOS: 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64

> show variables like "%packet%";
    max_allowed_packet       1048576    
    slave_max_allowed_packet  1073741824 

Windows 7 x64 (where it doesn't fail)
   MySQL: Server version: 5.1.47-community MySQL Community Server (GPL)
   PyMySQL (0.6.6)
   max_allowed_packet   1048576

**Comment by methane** [comment]
Setting max_allowed_packet more large solves your problem?

**Comment by methane** [comment]
Close this issue since no response for a long time.
