### ISSUE TITLE
TypeError: character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by Labouh** [PyMySQL/PyMySQL#415]
Hello,

pymysql in version 0.7 with python 2.7, converter throws an exception when applied on unicode (tested on ubuntu or windows 7 with the same exception!)

Here a simple example:

```py
> import pymysql
pymysql.__version__
'0.7.0.None'
from pymysql import converters 
converters.escape_string(u'test') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pymysql\converters.py", line 83, in escape_string
    return escape_unicode(value)
  File "C:\Python27\lib\site-packages\pymysql\converters.py", line 111, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "C:\Python27\lib\site-packages\pymysql\converters.py", line 74, in _escape_unicode
    return value.translate(_escape_table)
TypeError: character mapping must return integer, None or unicode
```

So we should downgrad in previous version because we are using unicode string and converter is called from cursor.callproc for instance (the real exception we get comes from callproc) !

Regards

**Comment by khamin** [comment]
Hello,

I have the same problem with 0.7
0.6.7 works fine.
