### ISSUE TITLE
Some data break protocol parse

### ISSUE THREAD

**Issue by tonal** [PyMySQL/PyMySQL#444]
code:
```pycon
$ipython3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
Type "copyright", "credits" or "license" for more information.
In [1]: import pymysql

In [2]: conn = pymysql.connect(read_default_file='.my.cnf', charset='utf8')

In [3]: curs = conn.cursor()

In [4]: curs.execute('SELECT * FROM ep_price_inet_reg_code ORDER BY idgood_rival')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-11fe6e8de2d8> in <module>()
----> 1 curs.execute('SELECT * FROM ep_price_inet_reg_code ORDER BY idgood_rival')

/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py in execute(self, query, args)
    144         query = self.mogrify(query, args)
    145 
--> 146         result = self._query(query)
    147         self._executed = query
    148         return result

/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py in _query(self, q)
    294         conn = self._get_db()
    295         self._last_executed = q
--> 296         conn.query(q)
    297         self._do_get_result()
    298         return self.rowcount

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in query(self, sql, unbuffered)
    817                 sql = sql.encode(self.encoding, 'surrogateescape')
    818         self._execute_command(COMMAND.COM_QUERY, sql)
--> 819         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    820         return self._affected_rows
    821 

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
    999         else:
   1000             result = MySQLResult(self)
-> 1001             result.read()
   1002         self._result = result
   1003         if result.server_status is not None:

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in read(self)
   1290                 self._read_load_local_packet(first_packet)
   1291             else:
-> 1292                 self._read_result_packet(first_packet)
   1293         finally:
   1294             self.connection = None

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_result_packet(self, first_packet)
   1345         self.field_count = first_packet.read_length_encoded_integer()
   1346         self._get_descriptions()
-> 1347         self._read_rowdata_packet()
   1348 
   1349     def _read_rowdata_packet_unbuffered(self):

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_rowdata_packet(self)
   1383                 self.connection = None  # release reference to kill cyclic reference.
   1384                 break
-> 1385             rows.append(self._read_row_from_packet(packet))
   1386 
   1387         self.affected_rows = len(rows)

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_row_from_packet(self, packet)
   1394             if data is not None:
   1395                 if encoding is not None:
-> 1396                     data = data.decode(encoding)
   1397                 if DEBUG: print("DEBUG: DATA = ", data)
   1398                 if converter is not None:

/usr/lib/python3.4/encodings/cp1251.py in decode(self, input, errors)
     13 
     14     def decode(self,input,errors='strict'):
---> 15         return codecs.charmap_decode(input,errors,decoding_table)
     16 
     17 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 134: character maps to <undefined>

In [5]: curs.execute('SELECT count(*) FROM ep_price_inet_reg_code ORDER BY idgood_rival')
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-6-e96a24f799e1> in <module>()
----> 1 curs.execute('SELECT count(*) FROM ep_price_inet_reg_code ORDER BY idgood_rival')

/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py in execute(self, query, args)
    144         query = self.mogrify(query, args)
    145 
--> 146         result = self._query(query)
    147         self._executed = query
    148         return result

/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py in _query(self, q)
    294         conn = self._get_db()
    295         self._last_executed = q
--> 296         conn.query(q)
    297         self._do_get_result()
    298         return self.rowcount

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in query(self, sql, unbuffered)
    817                 sql = sql.encode(self.encoding, 'surrogateescape')
    818         self._execute_command(COMMAND.COM_QUERY, sql)
--> 819         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    820         return self._affected_rows
    821 

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
    999         else:
   1000             result = MySQLResult(self)
-> 1001             result.read()
   1002         self._result = result
   1003         if result.server_status is not None:

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in read(self)
   1283     def read(self):
   1284         try:
-> 1285             first_packet = self.connection._read_packet()
   1286 
   1287             if first_packet.is_ok_packet():

/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py in _read_packet(self, packet_type)
    950             if packet_number != self._next_seq_id:
    951                 raise err.InternalError("Packet sequence number wrong - got %d expected %d" %
--> 952                     (packet_number, self._next_seq_id))
    953             self._next_seq_id = (self._next_seq_id + 1) % 256
    954 

InternalError: Packet sequence number wrong - got 252 expected 1

```
Table shema:
```sql
CREATE TABLE `ep_price_inet_reg_code` (
  `www_full` varchar(255) NOT NULL DEFAULT '',
  `idgood` varchar(255) NOT NULL,
  `idgood_rival` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  KEY `www_full` (`www_full`),
  KEY `idgood_rival` (`idgood_rival`)
) ENGINE=InnoDB DEFAULT CHARSET=cp1251;
```
In table ~1.6E6 rows
If replace pymysql to MySQLdb all work Ok.

**Comment by methane** [comment]
Could you find the row causing this problem and give me it?
I don't use encodings except utf8 and utf8mb4.  Both of PyMySQL and mysqlclient-python are tested only with utf8mb4.

**Comment by tonal** [comment]
I build minimal sample:
Create table and insert bad value:
```sql
CREATE TABLE `new_table` (
  `k` int(11) NOT NULL AUTO_INCREMENT,
  `v` text CHARACTER SET cp1251,
  PRIMARY KEY (`k`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `test`.`new_table` (`v`) VALUES (CONCAT('Opa', 0x98, 'Ups'));
```
Open connect and select all rows:
```python
>>> import pymysql                                                                                                    
>>> conn = pymysql.connect(database='test', charset='cp1251')                                                         
>>> curs = conn.cursor()                                                                                              
>>> SQL = 'SELECT * FROM new_table'                                                                                   
>>> curs.execute(SQL)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1292, in read
    self._read_result_packet(first_packet)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1347, in _read_result_packet
    self._read_rowdata_packet()
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1385, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1396, in _read_row_from_packet
    data = data.decode(encoding)
  File "/usr/lib/python3.4/encodings/cp1251.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 3: character maps to <undefined>
>>> curs.execute('SELECT count() FROM new_table')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/home/tonal/.local/lib/python3.4/site-packages/pymysql/connections.py", line 952, in _read_packet
    (packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 6 expected 1
```

**Comment by methane** [comment]
Thanks!

**Comment by methane** [comment]
```
In [2]: data  = b'Opa\x98Ups'

In [3]: data.decode('cp1251')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-51673a6932a3> in <module>()
----> 1 data.decode('cp1251')

/usr/local/bin/../Cellar/python3/3.5.1/bin/../Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/cp1251.py in decode(self, input, errors)
     13
     14     def decode(self,input,errors='strict'):
---> 15         return codecs.charmap_decode(input,errors,decoding_table)
     16
     17 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 3: character maps to <undefined>
```

It's not a bug.  Your data is wrong.
`use_unicode=False` may help you.  But I think you should fix your **data**.

**Comment by tonal** [comment]
Sorry.
This data placed in table. Server work with its date. MySQLdb work with its date.
Bat PyMySQL break all talk with server afte try fethch this date.
I do not write code for correct skip this date...
