### ISSUE TITLE
MemoryError on PyPy for >= 0.7

### ISSUE THREAD

**Issue by jamadden** [PyMySQL/PyMySQL#474]
Under all versions >= 0.7, PyPy (versions 2.5.0, 4.0.0, 4.0.1, 5.0.0 and 5.3.0, tested on both OS X and Linux) raises a MemoryError:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/ZODB/tests/MTStorage.py", line 227, in check2ZODBThreads
    db = ZODB.DB(self._storage)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/ZODB/DB.py", line 458, in __init__
    temp_storage.tpc_vote(t)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "relstorage/storage.py", line 841, in tpc_vote
    return self._vote()
  File "relstorage/storage.py", line 875, in _vote
    self._prepare_tid()
  File "relstorage/storage.py", line 757, in _prepare_tid
    adapter.txncontrol.add_transaction(cursor, tid_int, user, desc, ext)
  File "relstorage/adapters/txncontrol.py", line 140, in add_transaction
    self.Binary(description), self.Binary(extension)))
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/cursors.py", line 159, in execute
    query = self.mogrify(query, args)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/cursors.py", line 138, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/cursors.py", line 113, in _escape_args
    return tuple(conn.escape(arg) for arg in args)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/cursors.py", line 113, in <genexpr>
    return tuple(conn.escape(arg) for arg in args)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/connections.py", line 793, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/converters.py", line 26, in escape_item
    val = encoder(val, mapping)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/converters.py", line 94, in escape_bytes
    return b"_binary'%s'" % escape_string(value)
  File "/home/travis/virtualenv/pypy-2.5.0/site-packages/pymysql/converters.py", line 83, in escape_string
    value = value.replace('\\', '\\\\')
MemoryError
```

This same code works correctly with 0.6.6.

This is demonstrated by the [RelStorage tests on TravisCI](https://travis-ci.org/zodb/relstorage/jobs/137257113).

I don't have a shorter example yet but I can try to come up with one if that's helpful. 

I don't have any suggested fixes yet (for now we'll just pin to 0.6.6) but I might try to find one later.

**Comment by jamadden** [comment]
In this case, `value` is `bytearray()`. This crashes simply in PyPy, so this may just be a PyPy bug:
```python
>>>> bytearray().replace('\\', '\\\\')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

**Comment by jamadden** [comment]
Yes, this appears to be a [pypy bug](https://bitbucket.org/pypy/pypy/issues/2324/bytearray-replace-a-bc-raises-memoryerror).
