### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by jinleileiking** [PyMySQL/PyMySQL#486]
```
Traceback (most recent call last):
  File "producer.py", line 44, in <module>
    result = json.dumps(result)
  File "/usr/local/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 1, 24, 18, 11, 13) is not JSON serializable
```

update_time: 2016-01-24 17:45:53

  `update_time` datetime DEFAULT NULL,

**Comment by methane** [comment]
Yes, json can't serialize datetime.datetime, until you explicitly specify how to stringify it.
It's completely unrelated to PyMySQL.
