### ISSUE TITLE
Exception in substitution sequence as parametr for Python 3

### ISSUE THREAD

**Issue by tonal** [PyMySQL/PyMySQL#531]
## Current Behavior
```python
>>> curs.execute('SELECT 1 IN %s', ({1: 11, 2: 22, 3: 33}.keys(),))
...
AttributeError: 'dict_keys' object has no attribute 'translate'

>>> curs.execute('SELECT 1 IN %s', ({1: 11, 2: 22, 3: 33}.values(),))
...
AttributeError: 'dict_values' object has no attribute 'translate'
```
## Expected Behavior
```python
>>> curs.execute('SELECT 1 IN (1, 2, 3)')
1
>>> curs.execute('SELECT 1 IN %s', ([1, 2, 3],))
1
```

## Possible Solution
Add `dict_keys` and `dict_values` to pymysql.converters.encoders dictionary

## Executable script to reproduce (for bugs)

code:
```python
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db')

try:
    with connection.cursor() as curs:
        curs.execute('SELECT 1 IN (1, 2, 3)')
        curs.execute('SELECT 1 IN %s', ([1, 2, 3],))
        curs.execute('SELECT 1 IN %s', ({1: 11, 2: 22, 3: 33}.keys(),)) # bug 1
        curs.execute('SELECT 1 IN %s', ({1: 11, 2: 22, 3: 33}.values(),)) # # bug 2
finally:
    connection.close()
```

schema:
any

## Tracebacks (for bugs)

For bug 1:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 164, in execute
    query = self.mogrify(query, args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 118, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 118, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/connections.py", line 800, in literal
    return self.escape(obj, self.encoders)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/connections.py", line 793, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 110, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'dict_keys' object has no attribute 'translate'
```
For bug 2:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 164, in execute
    query = self.mogrify(query, args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 143, in mogrify
    query = query % self._escape_args(args, conn)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 118, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/cursors.py", line 118, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/connections.py", line 800, in literal
    return self.escape(obj, self.encoders)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/connections.py", line 793, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 110, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/home/tonal/lang/projects/promsoft/epool/props_service/venv/lib/python3.5/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'dict_values' object has no attribute 'translate'
```
## Your Environment
* Operating System and version: Kubuntu 16.04
* Python version and build: Python 3.5.2 (default, Aug 26 2016, 15:59:52) [GCC 5.4.0 20160609] on linux
* PyMySQL Version used: 0.7.9

**Comment by methane** [comment]
I don't want to do it.
Supporting only very common basic sequence type (list and tuple) make sense.
Supporting all sequence types make sense too, if it can be done without any downside.
But supporting uncommon types individually doesn't make sense.

You can convert it easily.

**Comment by mark-streami** [comment]
@methane a bit outdated but any possibility this could be reconsidered?
the pep documentation referred to under Resources (https://www.python.org/dev/peps/pep-0249/#paramstyle ) mention "pyformat" as one of the preferred ways of formatting since it offers clarity and readability (it seems to be especially effective when reading the query by itself when the params are separated to another file and when there are repeated params) and the only way to insert keyword based arguments seems to be through dictionaries..

**Comment by hjkwon0609** [comment]
@methane a bit outdated but any possibility this could be reconsidered?
the pep documentation referred to under Resources (https://www.python.org/dev/peps/pep-0249/#paramstyle ) mention "pyformat" as one of the preferred ways of formatting since it offers clarity and readability (it seems to be especially effective when reading the query by itself when the params are separated to another file and when there are repeated params) and the only way to insert keyword based arguments seems to be through dictionaries so it doesn't seem like an uncommon type

**Comment by methane** [comment]
@hjkwon0609 I think you are totally misunderstainding the issue.
PyMySQL supports pyformat. You can use dict parameter like `cur.query("SELECT %(a)s + %(b)s", {"a":42, "b":100})`.
This issue is about not dict, but dict_keys and dict_values.

**Comment by hjkwon0609** [comment]
@methane oh my bad you're right
