### ISSUE TITLE
pymysql.err.OperationalError: (2014, 'Command Out of Sync') 

### ISSUE THREAD

**Issue by bfbd888** [PyMySQL/PyMySQL#563]
Envirment:
```
ubuntu
uwsgi
flask 0.12
peewee 2.8.5
pymysql 0.7.10

```

Codes in flask:
```
db_connections = [db_fetch, db_zb123]

class Database:
    @staticmethod
    def connect():
        for conn in db_connections:
            if conn.is_closed():
                conn.connect()

    @staticmethod
    def close():
        for conn in db_connections:
            if not conn.is_closed():
                conn.close()


@app.before_request
def before_req():
    Database.connect()

@app.teardown_request
def teardown_req(exc):
    Database.close()
```

Exception in uwsgi log file multiple.

```
Traceback (most recent call last):
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3754, in commit
    self.get_conn().commit()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 784, in commit
    self._read_ok_packet()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 765, in _read_ok_packet
    raise err.OperationalError(2014, "Command Out of Sync")
pymysql.err.OperationalError: (2014, 'Command Out of Sync')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3746, in execute_sql
    self.commit()
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3754, in commit
    self.get_conn().commit()
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3569, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3754, in commit
    self.get_conn().commit()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 784, in commit
    self._read_ok_packet()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 765, in _read_ok_packet
    raise err.OperationalError(2014, "Command Out of Sync")
peewee.OperationalError: (2014, 'Command Out of Sync')

During handling of the above exception, another exception occurred:
...
```

https://github.com/coleifer/peewee/issues/1236

**Comment by methane** [comment]
uwsgi config?
Your code seems wrong for multi thread.
Are you using multi process but not multi thread?

2017/04/04 午前8:47 "UltraGIS" <notifications@github.com>:

**Comment by bfbd888** [comment]
uwsgi.ini

master=true
processes=4
threads=2

Thanks very much, I will modify threads=1.

**Comment by bfbd888** [comment]
I have modified uwsgi.ini to :

```
master=true
processes=6
threads=1
```

But exception still occur in uwsgi.log

My connection define is:

`PooledMySQLDatabase(host=host, database='XXX', user='root', password='******', charset='utf8mb4',                               max_connections=32)
`

And the exception is like this:

```
Traceback (most recent call last):
  File "/env/flask/lib/python3.5/site-packages/peewee.py", line 3754, in commit
    self.get_conn().commit()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 784, in commit
    self._read_ok_packet()
  File "/env/flask/lib/python3.5/site-packages/pymysql/connections.py", line 765, in _read_ok_packet
    raise err.OperationalError(2014, "Command Out of Sync")
pymysql.err.OperationalError: (2014, 'Command Out of Sync')
```

**Comment by methane** [comment]
You need to create reproducible example, or at least detailed debug log including query
before the exception happens.

There is no evidence this is PyMySQL issue for now.  It's likely your application's issue.

**Comment by nanoric** [comment]
I have a same problem.
with the same env:
peewee + pymysql + uwsgi(multi processes. every process have only 1 thread running)

at the beginning, errors comes about 8 hours since uwsgi starts(about 10k queries). With there is more and more user, it crashes faster and faster. Now it will crash every hour.

I tried to use PooledMySQLConnection, but havn't solve this problem.

**Comment by methane** [comment]
You need to create reproducible example, or at least detailed debug log including query
before the exception happens.

There is no evidence this is PyMySQL issue for now. It's likely your application's issue.
