### ISSUE TITLE
pymysql + ssl + eventlet

### ISSUE THREAD

**Issue by zzzeek** [PyMySQL/PyMySQL#567]
So, this is a tricky one and I'm not really sure if this falls under eventlet, pymysql, or elsewhere, I apologize.

Just trying to read more than 800 or so rows is resulting in a hang.   Test script:

```
import eventlet
eventlet.monkey_patch()

import pymysql as mdb
import sys

print "Eventlet version: %s" % eventlet.__version__
print "pymysql version: %s" % mdb.__version__

con = mdb.connect(
                  host='overcloud-controller-0.internalapi.walrusdomain',
                  user='scott', passwd='tiger',
                  db='mike_test',
        # seems like it doesn't matter if I type "ssl_ca" which is wrong,
        # guess some default crt is used
        ssl={"ssl-ca": '/etc/ipa/ca.crt'},

)
cursor = con.cursor()

cursor.execute("drop table if exists foo_bar")
cursor.execute("create table foo_bar (x integer, y integer)")
cursor.executemany("insert into foo_bar (x, y) values (%(x)s, %(y)s)", [{"x": i, "y": i * 10} for i in range(2000)])

print "2000 rows inserted"

print "heres ten of them..."
cursor.execute("select x, y from foo_bar limit 10")
print cursor.fetchall()

print "wow great.  here's all 2000"
cursor.execute("select x, y from foo_bar ")
print cursor.fetchall()

```

when it runs, we see:

```
Eventlet version: 0.18.4
pymysql version: 0.7.11.None
2000 rows inserted
heres ten of them...
((0, 0), (1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90))
wow great.  here's all 2000

```

and then we're hung.  ctrl-C shows we are at:

```
^CTraceback (most recent call last):
  File "test.py", line 30, in <module>
    cursor.execute("select x, y from foo_bar ")
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1347, in read
    self._read_result_packet(first_packet)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1413, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1447, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1004, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/lib/python2.7/site-packages/pymysql/_socketio.py", line 59, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python2.7/site-packages/eventlet/green/ssl.py", line 221, in recv_into
    timeout_exc=timeout_exc('timed out'))
  File "/usr/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/usr/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "/usr/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 346, in run
    self.wait(sleep_time)
  File "/usr/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 85, in wait
    presult = self.do_poll(seconds)
  File "/usr/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 62, in do_poll
    return self.poll.poll(seconds)
KeyboardInterrupt

```

on our environment, if we read like 800 rows, it's OK, when we get to like 805 rows, then we start hitting the hang.  something is going wrong ssl-wise in conjunction w/ eventlet.

If you have insight on what might be happening here we can get eventlet folks involved.    I know you don't have a lot of resources so I'll see if i can point some openstack peeps at this as well.

**Comment by methane** [comment]
https://github.com/eventlet/eventlet/commit/8e92d15d266b78720d4cc780cd2878377dcf7775

How about this?

**Comment by zzzeek** [comment]
you're just making it so that next time I have another hard question I'm going to bother YOU first :)   yeah that looks significant

**Comment by JAORMX** [comment]
It does seem to work with eventlet 0.21. Thanks!
