### ISSUE TITLE
packet bigger than 'max_allowed_packet' error is lost.

### ISSUE THREAD

**Issue by jbdeboer** [PyMySQL/PyMySQL#580]
When I send a large blob to my server, the server closes the client's connection after sending the error:
```
#08S01 Got a packet bigger than 'max_allowed_packet' bytes.
```

However, PyMySQL (0.7.11) throws the error:
```
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 855, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 1102, in _execute_command
    self.write_packet(sql[:packet_size])
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 978, in write_packet
    self._write_bytes(data)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 1044, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
```

PyMySQL should expose the 'max_allowed_packet' error to the user instead of a generic 'broken pipe' error.

**Comment by methane** [comment]
Since the error happens while "sending" request, no chance to read the error from server.
You should check server's error log when you met such error.

**Comment by jbdeboer** [comment]
@methane The server sends the error to the client. PyMySQL fails to read the error from the socket.

**Comment by methane** [comment]
From client point of view, failing while sending.
If you can undestand, try other clients.  They will show same behavior.

**Comment by jbdeboer** [comment]
@methane I realize, it fails while sending, but when the server closes the connection, it *also* sends an informative error to the client. That  error should be propagated to the user if possible.

e.g. See the fix for this situation in jbdeboer/PyMySQL@99b46ba93a9d86198d7778f8ba83b4b2da70d69a, my tests now print the following exception which is much more helpful.

```
Traceback (most recent call last):
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 1038, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "max_packet_test.py", line 62, in <module>
    use_pymsql()
  File "max_packet_test.py", line 32, in use_pymsql
    longstr)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 854, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 1098, in _execute_command
    self._write_bytes(packet)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 1043, in _write_bytes
    self._read_packet()
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 1013, in _read_packet
    packet.check_error()
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/james/gits/PyMySQL/build/lib/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1153, "Got a packet bigger than 'max_allowed_packet' bytes")
```

**Comment by irufus** [comment]
I'm curious as to WHICH clients don't show max_allowed_packet error back to the user.

**Comment by jbdeboer** [comment]
@irufus I tried mysql.connector Python package (mysql-connector-python-rf) as well. It raises a simple "Broken pipe" error.

The ```mysql``` command will return an error, as expected:
```
$ cat max_packets.sql | mysql -u pra -h ebb.huronbox.com -p
ERROR 1153 (08S01) at line 3: Got a packet bigger than 'max_allowed_packet' bytes
```

**Comment by irufus** [comment]
Outside of the the python universe com.mysql.jdbc will throw a specific exception.

**Comment by methane** [comment]
@jbdeboer Your fix won't work nice when TCP connection closed by other reason.

Reading after send error introduce complexity into this library.
It means this library may be more unstable or unmaintenable.

**Comment by methane** [comment]
Mysql command line client (and libmysqlclient) doesn't try to read after send error.
It shows "ERROR 1153 ..." only after successful sending query.
Even when query is shorter than `max_allowed_packet`, send succeeds if the query fits in
client's send buffer and server's receive buffer (in kernel, not mysqld).

When query is long enough to fill kernel level socket buffer, mysql command line client
doesn't show ERROR 1153.

```
$ ls -lh select.sql 
-rw-r--r-- 1 inada-n inada-n 214K Jun 17 16:06 select.sql

$ sudo  mysql < select.sql 
ERROR 1153 (08S01) at line 1: Got a packet bigger than 'max_allowed_packet' bytes

$ vim select.sql  # make query bigger.

$ ls -lh select.sql 
-rw-r--r-- 1 inada-n inada-n 428K Jun 17 16:11 select.sql

$ sudo  mysql < select.sql 
ERROR 2006 (HY000) at line 1: MySQL server has gone away
```

**Comment by methane** [comment]
So both of libmysqlclient and PyMySQL shows "ERROR 1153" after successful write of
query longer than `max_allowed_packet`.
And both shows broken pipe error when query is long enough to fail to send.
**Both library has exactly same behavior**.
