### ISSUE TITLE
InternalError: Packet sequence number wrong

### ISSUE THREAD

**Issue by jenstroeger** [PyMySQL/PyMySQL#606]
I’m sorry but I am unable to reproduce this issue reliably, and I am at a loss as to what could cause this exception:
```
2017-09-28 18:13:17,765 ERROR [sqlalchemy.pool.QueuePool][b'uWSGIWorker1Core0'] Exception during reset or similar
Traceback (most recent call last):
  File "/var/www/…/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/var/www/…/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/var/www/…/lib64/python3.6/site-packages/pymysql/connections.py", line 1001, in _read_packet
    % (packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 102 expected 8
```
I see this error in different variations for the packet sequence.

If it helps, I’m running a [Pyramid](https://trypyramid.com/) web-server connected to [SQLAlchemy](https://www.sqlalchemy.org/) which uses the PyMySQL driver.

Any hint or tip to explain this issue is appreciated! (See also [SQLAlchemy mailing list for this issue](https://groups.google.com/forum/#!topic/sqlalchemy/QT_jIVPzsDA).)

**Comment by methane** [comment]
Generally, it is caused by bad threading or gevent usage.
I don't have time and motivation to support you.  (I'm not paid for this project, just a volunteer.)

At least, reproducible example is required for issue report.
Here is not suppor forum.

**Comment by jenstroeger** [comment]
Possibly related issues are https://github.com/PyMySQL/PyMySQL/issues/422, https://github.com/PyMySQL/PyMySQL/issues/423, and https://github.com/PyMySQL/PyMySQL/issues/425.

**Comment by jlherren** [comment]
In case any other frustrated Googlers end up here having this problem: I encountered this very error message simply because my DB permissions were not set up correctly. I spent an hour trying to validate that all pymysql operations were indeed contained inside one single thread until I figured out it was simply a permission problem... I fixed the permissions on the MariaDB end and then all worked fine.

**Comment by methane** [comment]
@jlherren It may be a bug.  Would you elaborate about the wrong permission, or would you provide tcpdump for the situation when you saw the error?
