### ISSUE TITLE
pymysql.err.ProgrammingError in version 0.8.0, but not 0.7.10

### ISSUE THREAD

**Issue by GavinHuttley** [PyMySQL/PyMySQL#637]
Using Python 3.6, Rocks 6.2 (CentOS 6.6), MySQL Server version: 5.7.11. Using the [attached script](https://github.com/PyMySQL/PyMySQL/files/1654164/pymysql_bug.py.gz) applied to the [attached sql file](https://github.com/PyMySQL/PyMySQL/files/1654160/saccharomyces_cerevisiae_core_84_4.sql.gz), version 0.8.0 returns:

```(py36) [gavin@gduserv ENSEMBLDB_TEST]$ python pymysql_bug.py 
Traceback (most recent call last):
  File "pymysql_bug.py", line 24, in <module>
    r = cursor.execute(sql)
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/gavin/miniconda3/envs/py36/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `alt_allele_attrib` (\n  `alt_allele_id` int(10) unsigned DEFAULT NU' at line 10")
(py36) [gavin@gduserv ENSEMBLDB_TEST]$ 
```
If I then:
```
$ pip install PyMYSQL==0.7.10
```
I get no failures...
```
(py36) [gavin@gduserv ENSEMBLDB_TEST]$ python pymysql_bug.py 
0
72
(py36) [gavin@gduserv ENSEMBLDB_TEST]$ 
```

**Comment by methane** [comment]
Have you read release note before filing issue?
https://github.com/PyMySQL/PyMySQL/blob/c51b47e3c6fa0d8b8090a6b25f7168ed68082dea/CHANGELOG#L12-L15
