### ISSUE TITLE
Error python server.py

### ISSUE THREAD

**Issue by jesusUgaz** [PyMySQL/PyMySQL#677]
**_lo que utilizo:_**

> - ***Virtualenv***
> 
> - ***Python 2.7***
> 
> - ***Homebrew -> contiene mariabd***
>  
> - ***macOS Sierra -> version 10.12.6***
>

**_Error la ejecutar el siguiente comando:_**

    (example) 16:19:56 jugaz ~/FrontEnd/Work/example [master !] $
        python server.py
        Traceback (most recent call last):
          File "server.py", line 7, in <module>
            from urls import urls
          File "/Users/jugaz/FrontEnd/Work/example/urls.py", line 4, in <module>
            import controllers.main as main
          File "/Users/jugaz/FrontEnd/Work/example/controllers/main.py", line 6, in <module>
            from tasks import send_mail
          File "/Users/jugaz/FrontEnd/Work/example/tasks.py", line 1, in <module>
            from celery import Celery
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/celery/__compat__.py", line 136, in __getattr__
            module = __import__(self._object_origins[name], None, None, [name])
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/celery/app/__init__.py", line 15, in <module>
            from celery import _state
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/celery/_state.py", line 20, in <module>
            from celery.utils.threads import LocalStack
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/celery/utils/__init__.py", line 23, in <module>
            from kombu.entity import Exchange, Queue
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/kombu/entity.py", line 10, in <module>
            from .abstract import MaybeChannelBound
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/kombu/abstract.py", line 12, in <module>
            from .connection import maybe_channel
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/kombu/connection.py", line 24, in <module>
            from .log import get_logger
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/kombu/log.py", line 7, in <module>
            from .utils import cached_property
          File "/Users/jugaz/FrontEnd/Work/example/lib/python2.7/site-packages/kombu/utils/__init__.py", line 17, in <module>
            from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
        ImportError: cannot import name _uuid_generate_random

**Comment by methane** [comment]
Why do you file an issue here?
Backtrace shows it's totally unrelated to this project.
Please use Stackoverflow before file an issue, if you don't know how to report an issue.
