### ISSUE TITLE
caching_sha2_password connection doesn't work on python2.7

### ISSUE THREAD

**Issue by Uyooo** [PyMySQL/PyMySQL#715]
Hello,

I am trying to execute the example code in https://pypi.org/project/PyMySQL/0.9.2/#example with MySQL 8.0.11 and the new plugin caching_sha2_password but I have an error during connection.

-> pip list | grep -i mysql
PyMySQL          0.9.2

With Python 3.6, no problem:
->python3.6 test.py
{'id': 1, 'password': 'very-secret'}

With python 2.7:
-> python2.7 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    cursorclass=pymysql.cursors.DictCursor)
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 704, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 974, in connect
    self._request_authentication()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1203, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, u"Access denied for user 'myuser'@'localhost' (using password: NO)")

**Comment by methane** [comment]
caching_sha2_password is tested with Python 2.

Do you exactly same example?
Your error says `(using password: NO)")` but the example used password.

**Comment by methane** [comment]
I can't reproduce.  Please add this snippet into top of your code and paste output to gist.

```
import pymysql
pymysql.connections.DEBUG = True
pymysql._auth.DEBUG = True
```
