### ISSUE TITLE
Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by rahilsh** [PyMySQL/PyMySQL#722]
We are using pg_chameleon for replicating data from MySQL to PostgreSQL and pg_chameleon is using PyMySQL internally. We are getting below error during replication. Can someone help us resolve this.

```2018-09-07 11:21:15 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True                                                                             
2018-09-07 11:21:15 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True                                                                             
2018-09-07 11:21:15 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True                                                                             
2018-09-07 11:21:15 MainProcess INFO global_lib.py (604): Checking if the replica for source mysql is stopped                                                           
2018-09-07 11:21:15 MainProcess INFO global_lib.py (614): Cleaning not processed batches for source mysql                                                               
2018-09-07 11:21:15 MainProcess DEBUG pg_lib.py (3194): Cleaning table t_log_replica_mysql_1                                                                            
2018-09-07 11:21:16 MainProcess DEBUG pg_lib.py (3194): Cleaning table t_log_replica_mysql_2                                                                            
2018-09-07 11:21:16 MainProcess INFO global_lib.py (545): Starting the replica daemons for source mysql                                                                 
2018-09-07 11:21:16 MainProcess DEBUG global_lib.py (554): Replica process for source mysql is running                                                                  
2018-09-07 11:21:16 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True                                                                             
2018-09-07 11:21:16 MainProcess DEBUG pg_lib.py (1236): Cleaning replayed batches for source mysql older than 1 day
2018-09-07 11:21:16 replay_replica DEBUG pg_lib.py (620): Changing the autocommit flag to True
2018-09-07 11:21:16 read_replica DEBUG pg_lib.py (620): Changing the autocommit flag to True
2018-09-07 11:21:16 read_replica DEBUG pg_lib.py (3066): Collecting schema mappings for source mysql
2018-09-07 11:21:16 read_replica DEBUG mysql_lib.py (1335): Batch data [(2478, 'mysql-bin-changelog.000113', 12010, 't_log_replica_mysql_1', '')]
2018-09-07 11:21:16 read_replica DEBUG mysql_lib.py (893): collecting table type map
2018-09-07 11:21:16 read_replica DEBUG mysql_lib.py (1105): GTID DISABLED - log_file mysql-bin-changelog.000113, log_position 12010. id_batch: 2478
2018-09-07 11:21:17 MainProcess ERROR global_lib.py (558): Read process alive: False - Replay process alive: True
2018-09-07 11:21:17 MainProcess ERROR global_lib.py (559): Stack trace: Traceback (most recent call last):
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py", line 487, in read_replica
    self.mysql_source.read_replica()
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1336, in read_replica
    replica_data=self.__read_replica_stream(batch_data)
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pg_chameleon/lib/mysql_lib.py", line 1107, in __read_replica_stream
    for binlogevent in my_stream:
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 413, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/log/bucardo/venv/lib64/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1236, 'Could not find first log file name in binary log index file')
2018-09-07 11:21:17 MainProcess ERROR global_lib.py (565): Read daemon crashed. Terminating the replay daemon.
2018-09-07 11:21:17 MainProcess DEBUG pg_lib.py (620): Changing the autocommit flag to True
2018-09-07 11:21:17 MainProcess INFO global_lib.py (590): Replica process for source mysql ended```

**Comment by methane** [comment]
This error message (`(1236, 'Could not find first log file name in binary log index file')`) is from MySQL.
You should ask somewhere like Stackoverflow or similar site.

I know MySQL client/server protocol, but I don't know about much about MySQL admin.

**Comment by rahilsh** [comment]
No problem thanks @methane
