### ISSUE TITLE
AttributeError in PyMySQL

### ISSUE THREAD

**Issue by Yajan** [PyMySQL/PyMySQL#728]
While executing a windows service which used pymysql I am getting this error:
Python 3.5
PyMySQL==0.9.2
```
Traceback (most recent call last):
  File "WindowsService.py", line 13, in <module>
    import pymysql as mysql
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pymysql\__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pymysql\err.py", line 94, in <module>
AttributeError: module 'pymysql.constants.ER' has no attribute 'CONSTRAINT_FAILED'
Failed to execute script WindowsService
```

**Comment by methane** [comment]
CONSTRAINT_FAILED exists.
Try clean install.

**Comment by Yajan** [comment]
Uninstalling the package and reinstalling it again solved the problem.
