### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 4 bytes

### ISSUE THREAD

**Issue by jaifiresong** [PyMySQL/PyMySQL#813]
Dear developers, I encountered a strange problem while working with pymysql. My code looks like this
```
db.cursor().execute('INSERT INTO t251 (`v1`,`v2`,`v3`) VALUES("a","b","c");')
db.commit()
```
environment
```
# pymysql 0.9.3
# python 3.6.5
# mysql 5.6
```
I got an exception as below
```
Traceback (most recent call last):
  File "E:\treasure\python\spider\douyin_spider\tools\MySQLHelper.py", line 77, in __query
    self.__cursor.execute(sql_str)
  File "C:\Python36\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python36\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python36\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python36\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "C:\Python36\lib\site-packages\pymysql\connections.py", line 1069, in read
    self._read_ok_packet(first_packet)
  File "C:\Python36\lib\site-packages\pymysql\connections.py", line 1103, in _read_ok_packet
    ok_packet = OKPacketWrapper(first_packet)
  File "C:\Python36\lib\site-packages\pymysql\protocol.py", line 293, in __init__
    self.server_status, self.warning_count = self.read_struct('<HH')
  File "C:\Python36\lib\site-packages\pymysql\protocol.py", line 182, in read_struct
    result = s.unpack_from(self._data, self._position)
struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by methane** [comment]
Try `pymysql.connections.DEBUG = True` before the query.
Packet dump will be printed.  Then post it on gist.

**Comment by jaifiresong** [comment]
> Try `pymysql.connections.DEBUG = True` before the query.
> Packet dump will be printed. Then post it on gist.

```
connected using socket
packet length: 78
call[1]: _read_packet (line 674)
call[2]: _get_server_information (line 966)
call[3]: connect (line 597)
call[4]: __init__ (line 327)
call[5]: Connect (line 94)
call[6]: __connect (line 94)
------------------------------------------------------------------
0A 35 2E 36 2E 31 36 2D 6C 6F 67 00 08 15 B5 02  .5.6.16-log.....
42 41 65 26 2B 23 52 5E 00 DF F7 21 02 00 0F 01  BAe&+#R^...!....
15 00 00 00 00 00 00 00 00 00 00 30 3B 53 33 46  ...........0;S3F
21 3C 2C 39 6B 68 61 00 6D 79 73 71 6C 5F 6E 61  !<,9kha.mysql_na
74 69 76 65 5F 70 61 73 73 77 6F 72 64 00        tive_password.
------------------------------------------------------------------

server_status: 2
salt_len: 21
packet length: 80
call[1]: write_packet (line 643)
call[2]: _request_authentication (line 851)
call[3]: connect (line 598)
call[4]: __init__ (line 327)
call[5]: Connect (line 94)
call[6]: __connect (line 94)
------------------------------------------------------------------
4C 00 00 01 0D A2 3A 00 FF FF FF 00 2D 00 00 00  L.....:.....-...
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00 00 00 00 6F 6E 69 6F 6E 70 6F 6C 61 72 64 62  ....onionpolardb
32 30 31 39 00 14 A8 88 5A 13 43 A6 9B F4 42 56  2019....Z.C...BV
5C 90 61 81 92 FB E9 3F BF 31 74 65 73 74 00 00  \.a....?.1test..
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: _request_authentication (line 852)
call[3]: connect (line 598)
call[4]: __init__ (line 327)
call[5]: Connect (line 94)
call[6]: __connect (line 94)
------------------------------------------------------------------
00 00 00 02 00 00 00                             .......
------------------------------------------------------------------

Succeed to auth
packet length: 23
call[1]: _execute_command (line 767)
call[2]: _send_autocommit_mode (line 406)
call[3]: autocommit (line 389)
call[4]: connect (line 611)
call[5]: __init__ (line 327)
call[6]: Connect (line 94)
------------------------------------------------------------------
13 00 00 00 03 53 45 54 20 41 55 54 4F 43 4F 4D  .....SET AUTOCOM
4D 49 54 20 3D 20 30                             MIT = 0
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: _read_ok_packet (line 396)
call[3]: _send_autocommit_mode (line 407)
call[4]: autocommit (line 389)
call[5]: connect (line 611)
call[6]: __init__ (line 327)
------------------------------------------------------------------
00 00 00 00 00 00 00                             .......
------------------------------------------------------------------

packet length: 22
call[1]: _execute_command (line 767)
call[2]: query (line 515)
call[3]: _query (line 328)
call[4]: execute (line 170)
call[5]: __connect (line 97)
call[6]: __init__ (line 38)
------------------------------------------------------------------
12 00 00 00 03 73 65 74 20 6E 61 6D 65 73 20 75  .....set names u
74 66 38 6D 62 34                                tf8mb4
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: read (line 1066)
call[3]: _read_query_result (line 727)
call[4]: query (line 516)
call[5]: _query (line 328)
call[6]: execute (line 170)
------------------------------------------------------------------
00 00 00 00 00 00 00                             .......
------------------------------------------------------------------

packet length: 59
call[1]: _execute_command (line 767)
call[2]: query (line 515)
call[3]: _query (line 328)
call[4]: execute (line 170)
call[5]: __query (line 77)
call[6]: insert (line 119)
------------------------------------------------------------------
37 00 00 00 03 49 4E 53 45 52 54 20 49 4E 54 4F  7....INSERT INTO
20 74 32 35 31 20 28 60 76 31 60 2C 60 76 32 60   t251 (`v1`,`v2`
2C 60 76 33 60 29 20 56 41 4C 55 45 53 28 22 61  ,`v3`) VALUES("a
22 2C 22 62 22 2C 22 63 22 29 3B                 ","b","c");
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: read (line 1066)
call[3]: _read_query_result (line 727)
call[4]: query (line 516)
call[5]: _query (line 328)
call[6]: execute (line 170)
------------------------------------------------------------------
00 01 FA 01 00 00 00                             .......
------------------------------------------------------------------

packet length: 11
call[1]: _execute_command (line 767)
call[2]: commit (line 421)
call[3]: __query (line 78)
call[4]: insert (line 119)
call[5]: <module> (line 16)
07 00 00 00 03 43 4F 4D 4D 49 54                 .....COMMIT
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: _read_ok_packet (line 396)
call[3]: commit (line 422)
call[4]: __query (line 78)
call[5]: insert (line 119)
call[6]: <module> (line 16)
------------------------------------------------------------------
00 00 00 00 00 00 00                             .......
------------------------------------------------------------------

0
packet length: 59
call[1]: _execute_command (line 767)
call[2]: query (line 515)
call[3]: _query (line 328)
call[4]: execute (line 170)
call[5]: __query (line 77)
call[6]: insert (line 119)
------------------------------------------------------------------
37 00 00 00 03 49 4E 53 45 52 54 20 49 4E 54 4F  7....INSERT INTO
20 74 32 35 31 20 28 60 76 31 60 2C 60 76 32 60   t251 (`v1`,`v2`
2C 60 76 33 60 29 20 56 41 4C 55 45 53 28 22 61  ,`v3`) VALUES("a
22 2C 22 62 22 2C 22 63 22 29 3B                 ","b","c");
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: read (line 1066)
call[3]: _read_query_result (line 727)
call[4]: query (line 516)
call[5]: _query (line 328)
call[6]: execute (line 170)
------------------------------------------------------------------
00 01 FC FB 00 01 00                             .......
------------------------------------------------------------------

packet length: 13
call[1]: _execute_command (line 767)
call[2]: rollback (line 431)
call[3]: __query (line 84)
call[4]: insert (line 119)
call[5]: <module> (line 16)
09 00 00 00 03 52 4F 4C 4C 42 41 43 4B           .....ROLLBACK
------------------------------------------------------------------

packet length: 7
call[1]: _read_packet (line 674)
call[2]: _read_ok_packet (line 396)
call[3]: rollback (line 432)
call[4]: __query (line 84)
call[5]: insert (line 119)
call[6]: <module> (line 16)
------------------------------------------------------------------
00 00 00 00 00 00 00                             .......
------------------------------------------------------------------
```

**Comment by methane** [comment]
Are the `struct.error` happened in this packet dump?


```
In [3]: packet = pymysql.protocol.MysqlPacket(b"\x00\x01\xfa\x01\x00\x00\x00", encoding='utf-8')

In [4]: packet.is_ok_packet()
Out[4]: True

In [5]: pymysql.protocol.OKPacketWrapper(packet)
Out[5]: <pymysql.protocol.OKPacketWrapper at 0x7fe63b1b36d0>
```

**Comment by jaifiresong** [comment]
> \x00\x01\xfa\x01\x00\x00\x00

Sorry the debugging information above is not correct.

I found an error in the following characters
```
packet = pymysql.protocol.MysqlPacket(b"\x00\01\xfc\xfb\x00\x01\x00", encoding='utf-8')

print(packet.is_ok_packet())

pymysql.protocol.OKPacketWrapper(packet)
```

**Comment by methane** [comment]
I need information about when / why MySQL sends such a packet.
Please provide packet capture when you received the packet.

**Comment by jaifiresong** [comment]
> I need information about when / why MySQL sends such a packet.
> Please provide packet capture when you received the packet.

So you're saying that under normal circumstances you don't get packets like this?And what's even more strange is that this error occurs when the written data increment ID is 251. Here is my TCP catch

```
0000   0c 9d 92 cb 0d fe bc 46 99 00 f5 12 08 00 45 00   .......F......E.
0010   00 33 05 e0 40 00 33 06 01 6a 78 1b e6 47 c0 a8   .3..@.3..jx..G..
0020   21 70 12 2d 16 b5 4f e0 58 1d be 10 8d 9c 50 18   !p.-..O.X.....P.
0030   00 e5 4d d5 00 00 07 00 00 01 00 01 fc fb 00 01   ..M.............
0040   00                                                .

```

**Comment by methane** [comment]
> So you're saying that under normal circumstances you don't get packets like this?

Of course!  I never saw or heard about such a situation.
Otherwise, I fixed it already.

> And what's even more strange is that this error occurs when the written data increment ID is 251.

Thank you for the hint.

**Comment by jaifiresong** [comment]
Thanks for your answer.

**Comment by methane** [comment]
> Here is my TCP catch

I can't find packet previous to "07 00 00 01 00 01 fc fb 00 01 00" in your capture.
Could you give me output of DEBUG=True, or pcap file (you can use Wireshark)?

**Comment by methane** [comment]
I confirmed "07 00 00 01 00 01 fc fb 00 01 00" is broken packet.

I have no idea why MySQL sends this.  But MySQL 5.6.16 is too old.  Please try upgrade MySQL.

**Comment by jaifiresong** [comment]
Thank you for your help, I have tried other versions of the database, is normal.
