### ISSUE TITLE
ping(reconnect=True) doesn't reconnect the database

### ISSUE THREAD

**Issue by Gugu7264** [PyMySQL/PyMySQL#847]
Hey,
I'm using the module in my discord bot, and I check the connection with `connection.ping(reconnect=True)` before my query. Then I create a cursor instance: `with connection.cursor() as cursor:`. It works for the 10 first minutes, then it raises `pymysql.err.InterfaceError: (0, '')` for each query.

Full traceback:
`Traceback (most recent call last):

  File "/home/bist1484/public_html/cgi-bin/commands_files/rank.py", line 66, in rank
    cursor.execute(sql)

  File "/home/bist1484/virtualenv/winterlounge/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)

  File "/home/bist1484/virtualenv/winterlounge/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)

  File "/home/bist1484/virtualenv/winterlounge/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)

  File "/home/bist1484/virtualenv/winterlounge/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")

pymysql.err.InterfaceError: (0, '')`

**Comment by Gugu7264** [comment]
The module was not imported in this file.
