### ISSUE TITLE
Questions about connecting IPv6

### ISSUE THREAD

**Issue by Zack0421** [PyMySQL/PyMySQL#853]
**Describe the bug**
Hi~I want to use ipv6 to connect to the mysql, but it fails.

Code:
```py
import pymysql
db = pymysql.connect(host="::1",
                     user="kedacom",
                     passwd="KedaMysql16#",
                     db="ap",
                     cursorclass=pymysql.cursors.DictCursor,
                     charset='utf8'
                    )
cursor = db.cursor()
cursor.execute("SELECT VERSION()")
data = cursor.fetchone()
print ("Database version : %s " % data)
db.close()
```

**Environment**
 - OS: centos 7.2 
 - Server and version: MySQL 5.7.25
 - PyMySQL version: 0.9.2

**Additional context**
Run shell command can make it connect successfully:
```
[root@6a9048a2-f3d1-11e9-923e-000c290dced9 bin]# mysql -h ::1 -ukedacom -pKedaMysql16#
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 46
Server version: 5.7.25-log MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
mysql> 
```
run py:
```
[root@6a9048a2-f3d1-11e9-923e-000c290dced9 bin]# ./python mytest.py 
Traceback (most recent call last):
  File "/opt/mcu/restapi/lib/python3.5/site-packages/pymysql/connections.py", line 582, in connect
    **kwargs)
  File "/opt/midware/python3/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/opt/midware/python3/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mytest.py", line 8, in <module>
    charset='utf8'
  File "/opt/mcu/restapi/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/opt/mcu/restapi/lib/python3.5/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/opt/mcu/restapi/lib/python3.5/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '::1' ([Errno 111] Connection refused)")
```

Is there a problem with my connection parameters?

**Comment by methane** [comment]
Maybe your Python is not build with IPv6 support?
Anyway, I don't know about your environment issue.

**Comment by Zack0421** [comment]
Looks like I can't connect successfully through the default port.
When I added the port, the connection was successful.
```
import pymysql
db = pymysql.connect(host="::1",
                     port=3306,
                     user="kedacom",
                     passwd="KedaMysql16#",
                     db="ap",
                     cursorclass=pymysql.cursors.DictCursor,
                     charset='utf8'
                    )
cursor = db.cursor()
cursor.execute("SELECT VERSION()")
data = cursor.fetchone()
print ("Database version : %s " % data)
db.close()
```
