### ISSUE TITLE
AssertionError: Protocol error, expecting EOF

### ISSUE THREAD

**Issue by shiritwaksman** [PyMySQL/PyMySQL#854]
Hello,

My system works fine with MySQLdb.
I wanted it to work with PyMySQL, and locally it worked fine, but on my production env I started to get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1082, in read
    self._read_result_packet(first_packet)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1151, in _read_result_packet
    self._get_descriptions()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1252, in _get_descriptions
    assert eof_packet.is_eof_packet(), 'Protocol error, expecting EOF'
AssertionError: Protocol error, expecting EOF
```

We are working with AWS RDS version 5.7.23 and PyMySQL 0.9.3.
It is important to note that in production we use python 2.7, but the code also supports python 3.8 using future lib.

**Comment by methane** [comment]
I stopped Python 2 support.  Future version will not support Python 2.

> but the code also supports python 3.8 using future lib.

OK, it's time to update your production env!

**Comment by david-verb** [comment]
@methane I am having the same issue with python3.6. PyMySQL version is 0.10.1

**Comment by methane** [comment]
> @methane I am having the same issue with python3.6. PyMySQL version is 0.10.1

Your information is not enough to reproduce your issue. Please report "full step" to reproduce, including schema, data, and runnable code (not snippet). If you can not provide it, packet dump (tcpdump or wireshark) may help to share what happened in you environment.

Generally speaking, such error means you are using this library in bad way. For example, using one connection in multiple threads/greenlets/processes. So I don't accept "I have an error" as issue report. It is just spam notification to me.
