### ISSUE TITLE
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1056)

### ISSUE THREAD

**Issue by kobe-tian** [PyMySQL/PyMySQL#862]
when I use pymysql to connect mysql , I got this error
PyMySQL == 0.6.7
python == 3.7.5
mysql == 5.7.23
openssl == 1.1.0j

Code:

```py
import pymysql
con = pymysql.connect(
    host='xxx',
    user='xxx',
    passwd="xxx",
    db='xxx',
    ssl={
        "ca": "xxxx",
        "cert": "xxxxx",
        "key": "xxxx",
    } 
)
con.cursor()
con.close()
```

```Error
Traceback (most recent call last):
  File "/home/linux/py3env/lib/python3.7/site-packages/pymysql/connections.py", line 851, in connect
    self._request_authentication()
  File "/home/linux/py3env/lib/python3.7/site-packages/pymysql/connections.py", line 1017, in _request_authentication
    ca_certs=self.ca)
  File "/home/linux/py3env/lib/python3.7/ssl.py", line 1222, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/home/linux/py3env/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/linux/py3env/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/home/linux/py3env/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1056)
```
any help will be greateful

**Comment by methane** [comment]
Your MySQL is using too old (danger) TLS version.
See this.
https://github.com/PyMySQL/PyMySQL/issues/817#issuecomment-572926098
