### ISSUE TITLE
module 'asyncio.streams' has no attribute 'IncompleteReadError'

### ISSUE THREAD

**Issue by Josephkready** [PyMySQL/PyMySQL#876]
**Describe the bug**
I am running multiple select queries against a database. 

The initial error is probably not your fault:
Traceback (most recent call last):
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 598, in _read_bytes
    data = await self._reader.readexactly(num_bytes)
  File "C:\Users\jkready\anaconda3\envs\main\lib\asyncio\streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 2002 bytes read on a total of 54192 expected bytes

But this seems to be not caught properly:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jkready\anaconda3\envs\main\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\jkready\anaconda3\envs\main\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\jkready\Documents\ReserachTools\cosmos_data_export\Classes\Connections.py", line 39, in _run_all
    [await f for f in tqdm(asyncio.as_completed(self.tasks),
  File "c:\Users\jkready\Documents\ReserachTools\cosmos_data_export\Classes\Connections.py", line 39, in <listcomp>
    [await f for f in tqdm(asyncio.as_completed(self.tasks),
  File "C:\Users\jkready\anaconda3\envs\main\lib\asyncio\tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "c:\Users\jkready\Documents\ReserachTools\cosmos_data_export\Classes\Connections.py", line 28, in create_task
    results = await self.exectue(query.query, query.data)
  File "c:\Users\jkready\Documents\ReserachTools\cosmos_data_export\Classes\Connections.py", line 58, in exectue
    else: await cur.execute(query)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 622, in _read_query_result
    await result.read()
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 1113, in read
    await self._read_result_packet(first_packet)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 1173, in _read_result_packet
    await self._read_rowdata_packet()
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 1208, in _read_rowdata_packet
    packet = await self.connection._read_packet()
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 580, in _read_packet
    recv_data = await self._read_bytes(bytes_to_read)
  File "C:\Users\jkready\anaconda3\envs\main\lib\site-packages\aiomysql\connection.py", line 599, in _read_bytes
    except asyncio.streams.IncompleteReadError as e:
AttributeError: module 'asyncio.streams' has no attribute 'IncompleteReadError'

**To Reproduce**
Complete steps to reproduce the behavior:

Schema:

```
CREATE DATABASE ...
CREATE TABLE ...
```

Code:

async def exectue(self, query, data):
        async with self.pool.acquire() as conn:
            async with conn.cursor() as cur:
                if data: await cur.execute(query, data) 
                else: await cur.execute(query) <- Breaks here
                records = await cur.fetchall()
        return {"header":[i[0] for i in cur.description], "data":records}

**Expected behavior**
Passing the error through instead of getting caught in an AttributeError:

**Environment**
 - OS: [e.g. Windows, Linux] Windows
 - Server and version: [e.g. MySQL 8.0.19, MariaDB] MySQL 8.0.19
 - PyMySQL version: 3.8

**Additional context**

**Comment by methane** [comment]
Why do you report here?
Please report it to aiomysql.
