### ISSUE TITLE
Can't pymysql set the case sensitivity?

### ISSUE THREAD

**Issue by avcatshy** [PyMySQL/PyMySQL#888]
Can't pymysql set the case sensitivity? When I query in uppercase letters, pymysql automatically converts the table name to lowercase.
```
--->Query string is : select Name, Age from blackHero where Country="US"
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    print(dbHandle.query("select Name, Age from blackHero where Country=%s"% country))
  File "/Users/z/Documents/ppymysql.py", line 66, in query
    return self.query_one(query, args)
  File "/Users/z/Documents/ppymysql.py", line 42, in query_one
    self.cursor.execute(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'superhero.blackhero' doesn't exist")
```
mysql shows like this：
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| superHero          |
+--------------------+
2 rows in set (0.00 sec)
mysql> show tables;
+-----------------------+
| Tables_in_superHero |
+-----------------------+
| blackHero             |
| blackMaster           |
+-----------------------+
12 rows in set (0.00 sec)
mysql> show variables like "%case%";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 0     |
+------------------------+-------+
2 rows in set (0.00 sec)
```

**Comment by methane** [comment]
> pymysql automatically converts the table name to lowercase.

Your suspection is wrong. PyMySQL doesn't convert query.
You should ask support on Python or MySQL forum, not here.
