### ISSUE TITLE
Unable to login with password greater than 19 characters when using caching_sha2_password authentication plugin

### ISSUE THREAD

**Issue by jcoetzee** [PyMySQL/PyMySQL#890]
**Describe the bug**
If a MySQL user uses sha2_password or caching_sha2_password authentication plugin and a password longer than 19 characters, attempts to connect to the database return Access Denied

**To Reproduce**
Complete steps to reproduce the behavior:
### Create user with 20 character password

    mysql> CREATE USER 'sha2user'@'%'
        -> IDENTIFIED WITH caching_sha2_password BY 'passwordpasswordpass';
    Query OK, 0 rows affected (0.31 sec)

### Test that user can login

    $ mysql -h <host> -u sha2user -ppasswordpasswordpass
    mysql: [Warning] Using a password on the command line interface can be insecure.
    Welcome to the MySQL monitor.  Commands end with ; or \g.
    Your MySQL connection id is 278
    Server version: 8.0.20 Source distribution

### Attempt to connect via pymysql

    >>> pymysql.connect(host='<host>', user='sha2user', password='passwordpasswordpass')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
        return Connection(*args, **kwargs)
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
        self.connect()
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 588, in connect
        self._request_authentication()
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 863, in _request_authentication
        auth_packet = self._process_auth(plugin_name, auth_packet)
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 892, in _process_auth
        return _auth.caching_sha2_password_auth(self, auth_packet)
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/_auth.py", line 324, in caching_sha2_password_auth
        pkt = _roundtrip(conn, data)
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/_auth.py", line 181, in _roundtrip
        pkt = conn._read_packet()
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
        packet.raise_for_error()
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
        err.raise_mysql_exception(self._data)
      File "/Users/user/tmp/venv/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
        raise errorclass(errno, errval)
    pymysql.err.OperationalError: (1045, "Access denied for user 'sha2user'@'<ip>' (using password: YES)")

### Set 19 character password for user

    mysql> ALTER USER 'sha2user'@'%' IDENTIFIED BY 'passwordpasswordpas';
    Query OK, 0 rows affected (0.25 sec)

### Check user can login

    $ mysql -h mysql.cbif1ihb6q5h.eu-west-1.rds.amazonaws.com -u sha2user -ppasswordpasswordpas
    mysql: [Warning] Using a password on the command line interface can be insecure.
    Welcome to the MySQL monitor.  Commands end with ; or \g.
    Your MySQL connection id is 281
    Server version: 8.0.20 Source distribution

### Connect via PyMySQL

    >>> pymysql.connect(host='mysql.cbif1ihb6q5h.eu-west-1.rds.amazonaws.com', user='sha2user', password='passwordpasswordpas')
    <pymysql.connections.Connection object at 0x102097610>

**Expected behavior**
The user should be able to login with a password >19 characters long

**Environment**
 - OS: Linux
 - Server and version: MySQL 8.0.20
 - PyMySQL version: 0.10.0

**Comment by methane** [comment]
I can use.

```
In [1]: import pymysql
In [2]: con = pymysql.connect(host="127.0.0.1", user="sha2user", password="passwordpasswordpass")
In [3]: con.get_server_info()
Out[3]: '8.0.21'
```

**Comment by jcoetzee** [comment]
Yes, I did replicate with exactly that example. This was a further replication of occurrence in a production environment.

**Comment by methane** [comment]
Can you reproduce it with docker MySQL?
Or is it AWS-only issue?

**Comment by methane** [comment]
I find how to reproduce (e.g. use ` --default-authentication-plugin=native_password` in server), and now understand what happened.

The [MySQL protocol doc](https://dev.mysql.com/doc/internals/en/connection-phase-packets.html
)  says auth plugin data is end by EOF, not NUL:

```
string[EOF]    auth plugin data
```

But MySQL source says:
https://github.com/mysql/mysql-server/blob/7d10c82196c8e45554f27c00681474a9fb86d137/sql/auth/sha2_password.cc#L939-L945


```
    Native authentication sent 20 bytes + '\0' character = 21 bytes.
    This plugin must do the same to stay consistent with historical behavior
```

So auth plugin data contains trailing NUL! I need to strip it.
