### ISSUE TITLE
Unable to login when using sha256_password targeting MySQL 5.7.27 and lower

### ISSUE THREAD

**Issue by jcoetzee** [PyMySQL/PyMySQL#893]
**Describe the bug**
Access Denied when attempting to authenticate to MySQL 5.7.27 (and lower - tested .19, .21 and .26) when the user is configured to use sha256_password authentication backend. 

**To Reproduce**
Complete steps to reproduce the behavior:

Docker:

```
$ docker run --name mysql-5.7.27 -e MYSQL_ROOT_PASSWORD=password -d -p 3306:3306 mysql:5.7.27
$ docker run --name mysql-5.7.28 -e MYSQL_ROOT_PASSWORD=password -d -p 3307:3306 mysql:5.7.28
```

Create sha256 user on each:

```sql
CREATE USER 'sha256user'@'%' IDENTIFIED WITH sha256_password BY 'password';
```

Test login:

```
$ mysql -h 127.0.0.1 -u sha256user -ppassword -P 3306
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 5.7.27 MySQL Community Server (GPL)

$ mysql -h 127.0.0.1 -u sha256user -ppassword -P 3307
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 6
Server version: 5.7.28 MySQL Community Server (GPL)
```

Code:

```pycon
>>> pymysql.connect(host='127.0.0.1', user='sha256user', password='password', port=3306)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 588, in connect
    self._request_authentication()
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 863, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 894, in _process_auth
    return _auth.sha256_password_auth(self, auth_packet)
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/_auth.py", line 230, in sha256_password_auth
    pkt = _roundtrip(conn, b'\1')
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/_auth.py", line 181, in _roundtrip
    pkt = conn._read_packet()
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/coetzj/tmp/venv/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'sha256user'@'172.17.0.1' (using password: YES)"

>>> pymysql.connect(host='127.0.0.1', user='sha256user', password='password', port=3307)
<pymysql.connections.Connection object at 0x10b496cd0
```

**Expected behavior**
I expect to be able to authenticate and returned a connection

**Environment**
 - OS: Linux
 - Server and version: MySQL 5.7.27
 - PyMySQL version: 0.10.1

**Additional context**
Possibly related to #890 however occurs regardless of password length.

**Comment by jcoetzee** [comment]
Not sure if this is related but this was discovered when attempting to authenticate to 5.7.19 AWS RDS instance, strangely enough it seems that authentication is successful for 5.7.21 onward (not 5.7.28 as per above) when authenticating to RDS instances.

**Comment by methane** [comment]
Could you reproduce it with Docker MySQL?

**Comment by jcoetzee** [comment]
I did reproduce in Docker, exact replication is in the issue (including Docker commands)

**Comment by jcoetzee** [comment]
Were you able to replicate this?

**Comment by methane** [comment]
OK, MySQL 5.7.27 use yaSSL and MySQL 5.7.28 use OpenSSL.
You can not use RSA encryption in yaSSL build. Solutions are:

* Upgrade MySQL after 5.7.28
* Build MySQL 5.7.27 with OpenSSL.
* Don't use sha256_password.
* Use encrypted connection.

See this document for detail.
https://dev.mysql.com/doc/refman/5.7/en/sha256-pluggable-authentication.html

**Comment by jcoetzee** [comment]
Makes sense. Out of interest, how is the mysql client still able to authenticate to 5.7.27 in that case?

**Comment by jcoetzee** [comment]
Assuming it's because client establishes an encrypted connection?

**Comment by methane** [comment]
Yes.
