### ISSUE TITLE
When Upgrading Django1.11 to Django latest

### ISSUE THREAD

**Issue by Abishek-Rajagopal-Commits** [PyMySQL/PyMySQL#897]
After Installing the Latest Django version
it asked me to upgrade Mysql clent as well
like

```
File "/usr/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 36, in <module>
    raise ImproperlyConfigured('mysqlclient 1.3.13 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.7.11.None.
```
I installed latest version by 
```
pip3.6 install mysqlclient
```
then im gettion this error,
```
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0uh58twu/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-0uh58twu/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-build-0uh58twu/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0uh58twu/mysqlclient/
```
pls help

**Environment**
```
OS: Ubuntu 18
Python: Python 3.6
MySQL: 5.7
Django : (2, 2, 0, 'final', 0)
```

**Comment by iOSHJH** [comment]
I have the same problem
