### ISSUE TITLE
pymysql.err.InterfaceError: (0, '')

### ISSUE THREAD

**Issue by iPurya** [PyMySQL/PyMySQL#906]
Hi there.. i'm using python3.8.5 and PyMySQL last version.. 
sometimes i'm getting this error, what is that mean ?
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "bot.py", line 241, in callback_handling
    res = get_proxy_info(Id)
  File "bot.py", line 191, in get_proxy_info
    cursor.execute(f'SELECT {query} FROM users_info WHERE id=%s',(Id))
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')
```

The second problem : 
i hosting MYSQL server on public IP and i have 2 different clients that connecting to this database with PyMySql. but when i'm inserting a row in a table with first client, the second one cannot get that row immediately, i should wait about 1 minute to get that. What should i do ?

**Comment by methane** [comment]
Maintainer is not free tech support. Don't ask support here.

>  sometimes i'm getting this error, what is that mean ?

Read the document and source code.

https://github.com/PyMySQL/PyMySQL/blob/37fd1e1b0126d75d80eef59c053f80634b09bd75/pymysql/connections.py#L738

**connection is closed. **



> The second problem :
> i hosting MYSQL server on public IP and i have 2 different clients that connecting to this database with PyMySql. but when i'm inserting a row in a table with first client, the second one cannot get that row immediately, i should wait about 1 minute to get that. What should i do ?

It is not relating this driver. Ask question elsewhere.
