### ISSUE TITLE
It throw this error when I try to reconnect MySQL time after time too fast

### ISSUE THREAD

**Issue by gaoyadianta** [PyMySQL/PyMySQL#908]
It throw error when I try to reconnect MySQL time after time too fast, stack traceback is like this:
```shell
Traceback (most recent call last):
  File "/Users/***/venv/lib/python3.6/site-packages/pymysql/connections.py", line 571, in connect
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monit.py", line 184, in <module>
    get_all_big_a_stock_history_price()
  File "monit.py", line 168, in get_all_big_a_stock_history_price
    ret = insert_one_big_a_stock_history_price(ts_code, ts_code, row[1][1], row[1][2], row[1][3], row[1][4], row[1][5], row[1][6], row[1][7], row[1][8], row[1][9], row[1][10])
  File "monit.py", line 111, in insert_one_big_a_stock_history_price
    con = connect_db()
  File "monit.py", line 23, in connect_db
    charset='utf8')
  File "/Users/***/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/Users/***/lib/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/Users/***/lib/python3.6/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (timed out)")
```
It look likes a pymysql error, isn't it.

My code is inserting multiple values to Mysql time after time. Before every insert operation, i will reconnect to Mysql and then after the insert operation, i will close the connection.
The problem disappeared when i add a time delay `time.sleep(0.01)` between two insert operation to MySQL

**Comment by methane** [comment]
> It look likes a pymysql error, isn't it.

It isn't.

The error is caused from OS. I don't know why because it's your environment.
Maybe, your OS, or MySQL server doesn't accept new connection high frequency. But I am not sure. It's your environment, not mine.
