### ISSUE TITLE
"with" context manager doesn't work

### ISSUE THREAD

**Issue by dashedman** [PyMySQL/PyMySQL#934]
**Bug**
Just taking example template and it's doesnt work

Code:

```py
import pymysql
from pymysql.cursors import DictCursor

def start():
    conn = pymysql.connect(
            host=host,
            user=user,
            password=password,
            database=db_name,
            cursorclass=DictCursor
        )

    with conn:
        with conn.cursor() as cursor:
            ...
            
start()
```

**Traceback**
```
Traceback (most recent call last):
  File "C:\path\main.py", line 351, in <module>
    start()
  File "C:\path\main.py", line 236, in start
    with conn:
AttributeError: __enter__
```

**Environment**
 - OS: Windows 10
 - Server and version: MySQL 8.0.13-4
 - PyMySQL version: 0.10.1
 - Python 3.8.2

**Comment by methane** [comment]
It's not a big.
Context manager is added in master branch. It is just not released yet.

**Comment by dashedman** [comment]
Why did they change the documentation ahead of time?

**Comment by methane** [comment]
Because they are automated pipelines.
