### ISSUE TITLE
Python2 Authentication plugin 'dialog' (None) not configured

### ISSUE THREAD

**Issue by KaibutsuX** [PyMySQL/PyMySQL#986]
Fresh Ubuntu installation (v16)

-  Created a brand new VM with a fresh Ubuntu live cd environment
- Install pip
- pip install pymysql

```
python -c "import pymysql; pymysql.connect('myserver', 'root', 'password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 679, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 891, in connect
    self._request_authentication()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1106, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1161, in _process_auth
    raise err.OperationalError(2059, "Authentication plugin '%s' (%r) not configured" % (plugin_name, handler))
pymysql.err.OperationalError: (2059, "Authentication plugin 'dialog' (None) not configured")
```

Environment

- OS: [Linux Ubuntu 16]
- Python [ 2.7.18 ]
- PyMySQL version: ALL - I have tried this scenario with basically all released pymysql versions and it give this same error in all newer versions, but in older it will complain about MariaDB not being supported by this client
- MySQL (MariaDB) server:
```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 5450860
Server version: 10.3.27-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others
```

**Comment by methane** [comment]
* Python2 is not supported.
* I don't know which auth plugin you are using. But [mysql_native_password](https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/) is the best option for compatibility.

**Comment by KaibutsuX** [comment]
Ok, so it's not supported but I should use this auth_plugin anyway?
